name = "solution_DudekPlatt_v3"
defaultTargets = ["Solution", "Shifts", "Bounds"]

[[require]]
name = "IEANTN"
path = "../.."

[[lean_lib]]
name = "Solution"
roots = ["Solution"]

[[lean_lib]]
name = "Shifts"
roots = ["Shifts"]

[[lean_lib]]
name = "Bounds"
roots = ["Bounds"]
