/-
Copyright (c) 2026 IEANTN contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Akula, PNT+ contributors
-/
import RS12.FixedCheck

/-! Generated by RS12FactorialBuildCertificate.py. Only
`factorial_certificate_04` is exported for the full-period join. -/

namespace RS12Factorial

set_option Elab.async false
set_option maxRecDepth 100000

set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_120120_120370_check : checkFixedBlock 120120 250 = true := by
  decide +kernel

private theorem factorial_block_120120_120370 : ∀ n : ℕ, 120120 ≤ n → n < 120370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_120120_120370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_120370_120620_check : checkFixedBlock 120370 250 = true := by
  decide +kernel

private theorem factorial_block_120370_120620 : ∀ n : ℕ, 120370 ≤ n → n < 120620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_120370_120620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_120620_120870_check : checkFixedBlock 120620 250 = true := by
  decide +kernel

private theorem factorial_block_120620_120870 : ∀ n : ℕ, 120620 ≤ n → n < 120870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_120620_120870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_120870_121120_check : checkFixedBlock 120870 250 = true := by
  decide +kernel

private theorem factorial_block_120870_121120 : ∀ n : ℕ, 120870 ≤ n → n < 121120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_120870_121120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_121120_121370_check : checkFixedBlock 121120 250 = true := by
  decide +kernel

private theorem factorial_block_121120_121370 : ∀ n : ℕ, 121120 ≤ n → n < 121370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_121120_121370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_121370_121620_check : checkFixedBlock 121370 250 = true := by
  decide +kernel

private theorem factorial_block_121370_121620 : ∀ n : ℕ, 121370 ≤ n → n < 121620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_121370_121620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_121620_121870_check : checkFixedBlock 121620 250 = true := by
  decide +kernel

private theorem factorial_block_121620_121870 : ∀ n : ℕ, 121620 ≤ n → n < 121870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_121620_121870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_121870_122120_check : checkFixedBlock 121870 250 = true := by
  decide +kernel

private theorem factorial_block_121870_122120 : ∀ n : ℕ, 121870 ≤ n → n < 122120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_121870_122120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_122120_122370_check : checkFixedBlock 122120 250 = true := by
  decide +kernel

private theorem factorial_block_122120_122370 : ∀ n : ℕ, 122120 ≤ n → n < 122370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_122120_122370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_122370_122620_check : checkFixedBlock 122370 250 = true := by
  decide +kernel

private theorem factorial_block_122370_122620 : ∀ n : ℕ, 122370 ≤ n → n < 122620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_122370_122620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_122620_122870_check : checkFixedBlock 122620 250 = true := by
  decide +kernel

private theorem factorial_block_122620_122870 : ∀ n : ℕ, 122620 ≤ n → n < 122870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_122620_122870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_122870_123120_check : checkFixedBlock 122870 250 = true := by
  decide +kernel

private theorem factorial_block_122870_123120 : ∀ n : ℕ, 122870 ≤ n → n < 123120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_122870_123120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_123120_123370_check : checkFixedBlock 123120 250 = true := by
  decide +kernel

private theorem factorial_block_123120_123370 : ∀ n : ℕ, 123120 ≤ n → n < 123370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_123120_123370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_123370_123620_check : checkFixedBlock 123370 250 = true := by
  decide +kernel

private theorem factorial_block_123370_123620 : ∀ n : ℕ, 123370 ≤ n → n < 123620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_123370_123620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_123620_123870_check : checkFixedBlock 123620 250 = true := by
  decide +kernel

private theorem factorial_block_123620_123870 : ∀ n : ℕ, 123620 ≤ n → n < 123870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_123620_123870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_123870_124120_check : checkFixedBlock 123870 250 = true := by
  decide +kernel

private theorem factorial_block_123870_124120 : ∀ n : ℕ, 123870 ≤ n → n < 124120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_123870_124120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_124120_124370_check : checkFixedBlock 124120 250 = true := by
  decide +kernel

private theorem factorial_block_124120_124370 : ∀ n : ℕ, 124120 ≤ n → n < 124370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_124120_124370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_124370_124620_check : checkFixedBlock 124370 250 = true := by
  decide +kernel

private theorem factorial_block_124370_124620 : ∀ n : ℕ, 124370 ≤ n → n < 124620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_124370_124620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_124620_124870_check : checkFixedBlock 124620 250 = true := by
  decide +kernel

private theorem factorial_block_124620_124870 : ∀ n : ℕ, 124620 ≤ n → n < 124870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_124620_124870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_124870_125120_check : checkFixedBlock 124870 250 = true := by
  decide +kernel

private theorem factorial_block_124870_125120 : ∀ n : ℕ, 124870 ≤ n → n < 125120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_124870_125120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_125120_125370_check : checkFixedBlock 125120 250 = true := by
  decide +kernel

private theorem factorial_block_125120_125370 : ∀ n : ℕ, 125120 ≤ n → n < 125370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_125120_125370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_125370_125620_check : checkFixedBlock 125370 250 = true := by
  decide +kernel

private theorem factorial_block_125370_125620 : ∀ n : ℕ, 125370 ≤ n → n < 125620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_125370_125620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_125620_125870_check : checkFixedBlock 125620 250 = true := by
  decide +kernel

private theorem factorial_block_125620_125870 : ∀ n : ℕ, 125620 ≤ n → n < 125870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_125620_125870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_125870_126120_check : checkFixedBlock 125870 250 = true := by
  decide +kernel

private theorem factorial_block_125870_126120 : ∀ n : ℕ, 125870 ≤ n → n < 126120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_125870_126120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_126120_126370_check : checkFixedBlock 126120 250 = true := by
  decide +kernel

private theorem factorial_block_126120_126370 : ∀ n : ℕ, 126120 ≤ n → n < 126370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_126120_126370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_126370_126620_check : checkFixedBlock 126370 250 = true := by
  decide +kernel

private theorem factorial_block_126370_126620 : ∀ n : ℕ, 126370 ≤ n → n < 126620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_126370_126620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_126620_126870_check : checkFixedBlock 126620 250 = true := by
  decide +kernel

private theorem factorial_block_126620_126870 : ∀ n : ℕ, 126620 ≤ n → n < 126870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_126620_126870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_126870_127120_check : checkFixedBlock 126870 250 = true := by
  decide +kernel

private theorem factorial_block_126870_127120 : ∀ n : ℕ, 126870 ≤ n → n < 127120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_126870_127120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_127120_127370_check : checkFixedBlock 127120 250 = true := by
  decide +kernel

private theorem factorial_block_127120_127370 : ∀ n : ℕ, 127120 ≤ n → n < 127370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_127120_127370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_127370_127620_check : checkFixedBlock 127370 250 = true := by
  decide +kernel

private theorem factorial_block_127370_127620 : ∀ n : ℕ, 127370 ≤ n → n < 127620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_127370_127620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_127620_127870_check : checkFixedBlock 127620 250 = true := by
  decide +kernel

private theorem factorial_block_127620_127870 : ∀ n : ℕ, 127620 ≤ n → n < 127870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_127620_127870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_127870_128120_check : checkFixedBlock 127870 250 = true := by
  decide +kernel

private theorem factorial_block_127870_128120 : ∀ n : ℕ, 127870 ≤ n → n < 128120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_127870_128120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_128120_128370_check : checkFixedBlock 128120 250 = true := by
  decide +kernel

private theorem factorial_block_128120_128370 : ∀ n : ℕ, 128120 ≤ n → n < 128370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_128120_128370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_128370_128620_check : checkFixedBlock 128370 250 = true := by
  decide +kernel

private theorem factorial_block_128370_128620 : ∀ n : ℕ, 128370 ≤ n → n < 128620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_128370_128620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_128620_128870_check : checkFixedBlock 128620 250 = true := by
  decide +kernel

private theorem factorial_block_128620_128870 : ∀ n : ℕ, 128620 ≤ n → n < 128870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_128620_128870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_128870_129120_check : checkFixedBlock 128870 250 = true := by
  decide +kernel

private theorem factorial_block_128870_129120 : ∀ n : ℕ, 128870 ≤ n → n < 129120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_128870_129120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_129120_129370_check : checkFixedBlock 129120 250 = true := by
  decide +kernel

private theorem factorial_block_129120_129370 : ∀ n : ℕ, 129120 ≤ n → n < 129370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_129120_129370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_129370_129620_check : checkFixedBlock 129370 250 = true := by
  decide +kernel

private theorem factorial_block_129370_129620 : ∀ n : ℕ, 129370 ≤ n → n < 129620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_129370_129620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_129620_129870_check : checkFixedBlock 129620 250 = true := by
  decide +kernel

private theorem factorial_block_129620_129870 : ∀ n : ℕ, 129620 ≤ n → n < 129870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_129620_129870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_129870_130120_check : checkFixedBlock 129870 250 = true := by
  decide +kernel

private theorem factorial_block_129870_130120 : ∀ n : ℕ, 129870 ≤ n → n < 130120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_129870_130120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_130120_130370_check : checkFixedBlock 130120 250 = true := by
  decide +kernel

private theorem factorial_block_130120_130370 : ∀ n : ℕ, 130120 ≤ n → n < 130370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_130120_130370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_130370_130620_check : checkFixedBlock 130370 250 = true := by
  decide +kernel

private theorem factorial_block_130370_130620 : ∀ n : ℕ, 130370 ≤ n → n < 130620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_130370_130620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_130620_130870_check : checkFixedBlock 130620 250 = true := by
  decide +kernel

private theorem factorial_block_130620_130870 : ∀ n : ℕ, 130620 ≤ n → n < 130870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_130620_130870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_130870_131120_check : checkFixedBlock 130870 250 = true := by
  decide +kernel

private theorem factorial_block_130870_131120 : ∀ n : ℕ, 130870 ≤ n → n < 131120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_130870_131120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_131120_131370_check : checkFixedBlock 131120 250 = true := by
  decide +kernel

private theorem factorial_block_131120_131370 : ∀ n : ℕ, 131120 ≤ n → n < 131370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_131120_131370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_131370_131620_check : checkFixedBlock 131370 250 = true := by
  decide +kernel

private theorem factorial_block_131370_131620 : ∀ n : ℕ, 131370 ≤ n → n < 131620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_131370_131620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_131620_131870_check : checkFixedBlock 131620 250 = true := by
  decide +kernel

private theorem factorial_block_131620_131870 : ∀ n : ℕ, 131620 ≤ n → n < 131870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_131620_131870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_131870_132120_check : checkFixedBlock 131870 250 = true := by
  decide +kernel

private theorem factorial_block_131870_132120 : ∀ n : ℕ, 131870 ≤ n → n < 132120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_131870_132120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_132120_132370_check : checkFixedBlock 132120 250 = true := by
  decide +kernel

private theorem factorial_block_132120_132370 : ∀ n : ℕ, 132120 ≤ n → n < 132370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_132120_132370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_132370_132620_check : checkFixedBlock 132370 250 = true := by
  decide +kernel

private theorem factorial_block_132370_132620 : ∀ n : ℕ, 132370 ≤ n → n < 132620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_132370_132620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_132620_132870_check : checkFixedBlock 132620 250 = true := by
  decide +kernel

private theorem factorial_block_132620_132870 : ∀ n : ℕ, 132620 ≤ n → n < 132870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_132620_132870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_132870_133120_check : checkFixedBlock 132870 250 = true := by
  decide +kernel

private theorem factorial_block_132870_133120 : ∀ n : ℕ, 132870 ≤ n → n < 133120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_132870_133120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_133120_133370_check : checkFixedBlock 133120 250 = true := by
  decide +kernel

private theorem factorial_block_133120_133370 : ∀ n : ℕ, 133120 ≤ n → n < 133370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_133120_133370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_133370_133620_check : checkFixedBlock 133370 250 = true := by
  decide +kernel

private theorem factorial_block_133370_133620 : ∀ n : ℕ, 133370 ≤ n → n < 133620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_133370_133620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_133620_133870_check : checkFixedBlock 133620 250 = true := by
  decide +kernel

private theorem factorial_block_133620_133870 : ∀ n : ℕ, 133620 ≤ n → n < 133870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_133620_133870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_133870_134120_check : checkFixedBlock 133870 250 = true := by
  decide +kernel

private theorem factorial_block_133870_134120 : ∀ n : ℕ, 133870 ≤ n → n < 134120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_133870_134120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_134120_134370_check : checkFixedBlock 134120 250 = true := by
  decide +kernel

private theorem factorial_block_134120_134370 : ∀ n : ℕ, 134120 ≤ n → n < 134370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_134120_134370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_134370_134620_check : checkFixedBlock 134370 250 = true := by
  decide +kernel

private theorem factorial_block_134370_134620 : ∀ n : ℕ, 134370 ≤ n → n < 134620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_134370_134620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_134620_134870_check : checkFixedBlock 134620 250 = true := by
  decide +kernel

private theorem factorial_block_134620_134870 : ∀ n : ℕ, 134620 ≤ n → n < 134870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_134620_134870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_134870_135120_check : checkFixedBlock 134870 250 = true := by
  decide +kernel

private theorem factorial_block_134870_135120 : ∀ n : ℕ, 134870 ≤ n → n < 135120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_134870_135120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_135120_135370_check : checkFixedBlock 135120 250 = true := by
  decide +kernel

private theorem factorial_block_135120_135370 : ∀ n : ℕ, 135120 ≤ n → n < 135370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_135120_135370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_135370_135620_check : checkFixedBlock 135370 250 = true := by
  decide +kernel

private theorem factorial_block_135370_135620 : ∀ n : ℕ, 135370 ≤ n → n < 135620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_135370_135620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_135620_135870_check : checkFixedBlock 135620 250 = true := by
  decide +kernel

private theorem factorial_block_135620_135870 : ∀ n : ℕ, 135620 ≤ n → n < 135870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_135620_135870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_135870_136120_check : checkFixedBlock 135870 250 = true := by
  decide +kernel

private theorem factorial_block_135870_136120 : ∀ n : ℕ, 135870 ≤ n → n < 136120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_135870_136120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_136120_136370_check : checkFixedBlock 136120 250 = true := by
  decide +kernel

private theorem factorial_block_136120_136370 : ∀ n : ℕ, 136120 ≤ n → n < 136370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_136120_136370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_136370_136620_check : checkFixedBlock 136370 250 = true := by
  decide +kernel

private theorem factorial_block_136370_136620 : ∀ n : ℕ, 136370 ≤ n → n < 136620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_136370_136620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_136620_136870_check : checkFixedBlock 136620 250 = true := by
  decide +kernel

private theorem factorial_block_136620_136870 : ∀ n : ℕ, 136620 ≤ n → n < 136870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_136620_136870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_136870_137120_check : checkFixedBlock 136870 250 = true := by
  decide +kernel

private theorem factorial_block_136870_137120 : ∀ n : ℕ, 136870 ≤ n → n < 137120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_136870_137120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_137120_137370_check : checkFixedBlock 137120 250 = true := by
  decide +kernel

private theorem factorial_block_137120_137370 : ∀ n : ℕ, 137120 ≤ n → n < 137370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_137120_137370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_137370_137620_check : checkFixedBlock 137370 250 = true := by
  decide +kernel

private theorem factorial_block_137370_137620 : ∀ n : ℕ, 137370 ≤ n → n < 137620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_137370_137620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_137620_137870_check : checkFixedBlock 137620 250 = true := by
  decide +kernel

private theorem factorial_block_137620_137870 : ∀ n : ℕ, 137620 ≤ n → n < 137870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_137620_137870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_137870_138120_check : checkFixedBlock 137870 250 = true := by
  decide +kernel

private theorem factorial_block_137870_138120 : ∀ n : ℕ, 137870 ≤ n → n < 138120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_137870_138120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_138120_138370_check : checkFixedBlock 138120 250 = true := by
  decide +kernel

private theorem factorial_block_138120_138370 : ∀ n : ℕ, 138120 ≤ n → n < 138370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_138120_138370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_138370_138620_check : checkFixedBlock 138370 250 = true := by
  decide +kernel

private theorem factorial_block_138370_138620 : ∀ n : ℕ, 138370 ≤ n → n < 138620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_138370_138620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_138620_138870_check : checkFixedBlock 138620 250 = true := by
  decide +kernel

private theorem factorial_block_138620_138870 : ∀ n : ℕ, 138620 ≤ n → n < 138870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_138620_138870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_138870_139120_check : checkFixedBlock 138870 250 = true := by
  decide +kernel

private theorem factorial_block_138870_139120 : ∀ n : ℕ, 138870 ≤ n → n < 139120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_138870_139120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_139120_139370_check : checkFixedBlock 139120 250 = true := by
  decide +kernel

private theorem factorial_block_139120_139370 : ∀ n : ℕ, 139120 ≤ n → n < 139370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_139120_139370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_139370_139620_check : checkFixedBlock 139370 250 = true := by
  decide +kernel

private theorem factorial_block_139370_139620 : ∀ n : ℕ, 139370 ≤ n → n < 139620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_139370_139620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_139620_139870_check : checkFixedBlock 139620 250 = true := by
  decide +kernel

private theorem factorial_block_139620_139870 : ∀ n : ℕ, 139620 ≤ n → n < 139870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_139620_139870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_139870_140120_check : checkFixedBlock 139870 250 = true := by
  decide +kernel

private theorem factorial_block_139870_140120 : ∀ n : ℕ, 139870 ≤ n → n < 140120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_139870_140120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_140120_140370_check : checkFixedBlock 140120 250 = true := by
  decide +kernel

private theorem factorial_block_140120_140370 : ∀ n : ℕ, 140120 ≤ n → n < 140370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_140120_140370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_140370_140620_check : checkFixedBlock 140370 250 = true := by
  decide +kernel

private theorem factorial_block_140370_140620 : ∀ n : ℕ, 140370 ≤ n → n < 140620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_140370_140620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_140620_140870_check : checkFixedBlock 140620 250 = true := by
  decide +kernel

private theorem factorial_block_140620_140870 : ∀ n : ℕ, 140620 ≤ n → n < 140870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_140620_140870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_140870_141120_check : checkFixedBlock 140870 250 = true := by
  decide +kernel

private theorem factorial_block_140870_141120 : ∀ n : ℕ, 140870 ≤ n → n < 141120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_140870_141120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_141120_141370_check : checkFixedBlock 141120 250 = true := by
  decide +kernel

private theorem factorial_block_141120_141370 : ∀ n : ℕ, 141120 ≤ n → n < 141370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_141120_141370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_141370_141620_check : checkFixedBlock 141370 250 = true := by
  decide +kernel

private theorem factorial_block_141370_141620 : ∀ n : ℕ, 141370 ≤ n → n < 141620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_141370_141620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_141620_141870_check : checkFixedBlock 141620 250 = true := by
  decide +kernel

private theorem factorial_block_141620_141870 : ∀ n : ℕ, 141620 ≤ n → n < 141870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_141620_141870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_141870_142120_check : checkFixedBlock 141870 250 = true := by
  decide +kernel

private theorem factorial_block_141870_142120 : ∀ n : ℕ, 141870 ≤ n → n < 142120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_141870_142120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_142120_142370_check : checkFixedBlock 142120 250 = true := by
  decide +kernel

private theorem factorial_block_142120_142370 : ∀ n : ℕ, 142120 ≤ n → n < 142370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_142120_142370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_142370_142620_check : checkFixedBlock 142370 250 = true := by
  decide +kernel

private theorem factorial_block_142370_142620 : ∀ n : ℕ, 142370 ≤ n → n < 142620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_142370_142620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_142620_142870_check : checkFixedBlock 142620 250 = true := by
  decide +kernel

private theorem factorial_block_142620_142870 : ∀ n : ℕ, 142620 ≤ n → n < 142870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_142620_142870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_142870_143120_check : checkFixedBlock 142870 250 = true := by
  decide +kernel

private theorem factorial_block_142870_143120 : ∀ n : ℕ, 142870 ≤ n → n < 143120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_142870_143120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_143120_143370_check : checkFixedBlock 143120 250 = true := by
  decide +kernel

private theorem factorial_block_143120_143370 : ∀ n : ℕ, 143120 ≤ n → n < 143370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_143120_143370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_143370_143620_check : checkFixedBlock 143370 250 = true := by
  decide +kernel

private theorem factorial_block_143370_143620 : ∀ n : ℕ, 143370 ≤ n → n < 143620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_143370_143620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_143620_143870_check : checkFixedBlock 143620 250 = true := by
  decide +kernel

private theorem factorial_block_143620_143870 : ∀ n : ℕ, 143620 ≤ n → n < 143870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_143620_143870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_143870_144120_check : checkFixedBlock 143870 250 = true := by
  decide +kernel

private theorem factorial_block_143870_144120 : ∀ n : ℕ, 143870 ≤ n → n < 144120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_143870_144120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_144120_144370_check : checkFixedBlock 144120 250 = true := by
  decide +kernel

private theorem factorial_block_144120_144370 : ∀ n : ℕ, 144120 ≤ n → n < 144370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_144120_144370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_144370_144620_check : checkFixedBlock 144370 250 = true := by
  decide +kernel

private theorem factorial_block_144370_144620 : ∀ n : ℕ, 144370 ≤ n → n < 144620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_144370_144620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_144620_144870_check : checkFixedBlock 144620 250 = true := by
  decide +kernel

private theorem factorial_block_144620_144870 : ∀ n : ℕ, 144620 ≤ n → n < 144870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_144620_144870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_144870_145120_check : checkFixedBlock 144870 250 = true := by
  decide +kernel

private theorem factorial_block_144870_145120 : ∀ n : ℕ, 144870 ≤ n → n < 145120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_144870_145120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_145120_145370_check : checkFixedBlock 145120 250 = true := by
  decide +kernel

private theorem factorial_block_145120_145370 : ∀ n : ℕ, 145120 ≤ n → n < 145370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_145120_145370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_145370_145620_check : checkFixedBlock 145370 250 = true := by
  decide +kernel

private theorem factorial_block_145370_145620 : ∀ n : ℕ, 145370 ≤ n → n < 145620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_145370_145620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_145620_145870_check : checkFixedBlock 145620 250 = true := by
  decide +kernel

private theorem factorial_block_145620_145870 : ∀ n : ℕ, 145620 ≤ n → n < 145870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_145620_145870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_145870_146120_check : checkFixedBlock 145870 250 = true := by
  decide +kernel

private theorem factorial_block_145870_146120 : ∀ n : ℕ, 145870 ≤ n → n < 146120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_145870_146120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_146120_146370_check : checkFixedBlock 146120 250 = true := by
  decide +kernel

private theorem factorial_block_146120_146370 : ∀ n : ℕ, 146120 ≤ n → n < 146370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_146120_146370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_146370_146620_check : checkFixedBlock 146370 250 = true := by
  decide +kernel

private theorem factorial_block_146370_146620 : ∀ n : ℕ, 146370 ≤ n → n < 146620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_146370_146620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_146620_146870_check : checkFixedBlock 146620 250 = true := by
  decide +kernel

private theorem factorial_block_146620_146870 : ∀ n : ℕ, 146620 ≤ n → n < 146870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_146620_146870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_146870_147120_check : checkFixedBlock 146870 250 = true := by
  decide +kernel

private theorem factorial_block_146870_147120 : ∀ n : ℕ, 146870 ≤ n → n < 147120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_146870_147120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_147120_147370_check : checkFixedBlock 147120 250 = true := by
  decide +kernel

private theorem factorial_block_147120_147370 : ∀ n : ℕ, 147120 ≤ n → n < 147370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_147120_147370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_147370_147620_check : checkFixedBlock 147370 250 = true := by
  decide +kernel

private theorem factorial_block_147370_147620 : ∀ n : ℕ, 147370 ≤ n → n < 147620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_147370_147620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_147620_147870_check : checkFixedBlock 147620 250 = true := by
  decide +kernel

private theorem factorial_block_147620_147870 : ∀ n : ℕ, 147620 ≤ n → n < 147870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_147620_147870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_147870_148120_check : checkFixedBlock 147870 250 = true := by
  decide +kernel

private theorem factorial_block_147870_148120 : ∀ n : ℕ, 147870 ≤ n → n < 148120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_147870_148120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_148120_148370_check : checkFixedBlock 148120 250 = true := by
  decide +kernel

private theorem factorial_block_148120_148370 : ∀ n : ℕ, 148120 ≤ n → n < 148370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_148120_148370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_148370_148620_check : checkFixedBlock 148370 250 = true := by
  decide +kernel

private theorem factorial_block_148370_148620 : ∀ n : ℕ, 148370 ≤ n → n < 148620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_148370_148620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_148620_148870_check : checkFixedBlock 148620 250 = true := by
  decide +kernel

private theorem factorial_block_148620_148870 : ∀ n : ℕ, 148620 ≤ n → n < 148870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_148620_148870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_148870_149120_check : checkFixedBlock 148870 250 = true := by
  decide +kernel

private theorem factorial_block_148870_149120 : ∀ n : ℕ, 148870 ≤ n → n < 149120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_148870_149120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_149120_149370_check : checkFixedBlock 149120 250 = true := by
  decide +kernel

private theorem factorial_block_149120_149370 : ∀ n : ℕ, 149120 ≤ n → n < 149370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_149120_149370_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_149370_149620_check : checkFixedBlock 149370 250 = true := by
  decide +kernel

private theorem factorial_block_149370_149620 : ∀ n : ℕ, 149370 ≤ n → n < 149620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_149370_149620_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_149620_149870_check : checkFixedBlock 149620 250 = true := by
  decide +kernel

private theorem factorial_block_149620_149870 : ∀ n : ℕ, 149620 ≤ n → n < 149870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_149620_149870_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_149870_150120_check : checkFixedBlock 149870 250 = true := by
  decide +kernel

private theorem factorial_block_149870_150120 : ∀ n : ℕ, 149870 ≤ n → n < 150120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_149870_150120_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_150120_150150_check : checkFixedBlock 150120 30 = true := by
  decide +kernel

private theorem factorial_block_150120_150150 : ∀ n : ℕ, 150120 ≤ n → n < 150150 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_150120_150150_check hlo hhi


private theorem factorial_join_120370_120870 : ∀ n : ℕ, 120370 ≤ n → n < 120870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_120370_120620 factorial_block_120620_120870


private theorem factorial_join_120120_120870 : ∀ n : ℕ, 120120 ≤ n → n < 120870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_120120_120370 factorial_join_120370_120870


private theorem factorial_join_120870_121370 : ∀ n : ℕ, 120870 ≤ n → n < 121370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_120870_121120 factorial_block_121120_121370


private theorem factorial_join_121370_121870 : ∀ n : ℕ, 121370 ≤ n → n < 121870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_121370_121620 factorial_block_121620_121870


private theorem factorial_join_120870_121870 : ∀ n : ℕ, 120870 ≤ n → n < 121870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_120870_121370 factorial_join_121370_121870


private theorem factorial_join_120120_121870 : ∀ n : ℕ, 120120 ≤ n → n < 121870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_120120_120870 factorial_join_120870_121870


private theorem factorial_join_121870_122370 : ∀ n : ℕ, 121870 ≤ n → n < 122370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_121870_122120 factorial_block_122120_122370


private theorem factorial_join_122370_122870 : ∀ n : ℕ, 122370 ≤ n → n < 122870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_122370_122620 factorial_block_122620_122870


private theorem factorial_join_121870_122870 : ∀ n : ℕ, 121870 ≤ n → n < 122870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_121870_122370 factorial_join_122370_122870


private theorem factorial_join_122870_123370 : ∀ n : ℕ, 122870 ≤ n → n < 123370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_122870_123120 factorial_block_123120_123370


private theorem factorial_join_123370_123870 : ∀ n : ℕ, 123370 ≤ n → n < 123870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_123370_123620 factorial_block_123620_123870


private theorem factorial_join_122870_123870 : ∀ n : ℕ, 122870 ≤ n → n < 123870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_122870_123370 factorial_join_123370_123870


private theorem factorial_join_121870_123870 : ∀ n : ℕ, 121870 ≤ n → n < 123870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_121870_122870 factorial_join_122870_123870


private theorem factorial_join_120120_123870 : ∀ n : ℕ, 120120 ≤ n → n < 123870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_120120_121870 factorial_join_121870_123870


private theorem factorial_join_124120_124620 : ∀ n : ℕ, 124120 ≤ n → n < 124620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_124120_124370 factorial_block_124370_124620


private theorem factorial_join_123870_124620 : ∀ n : ℕ, 123870 ≤ n → n < 124620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_123870_124120 factorial_join_124120_124620


private theorem factorial_join_124620_125120 : ∀ n : ℕ, 124620 ≤ n → n < 125120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_124620_124870 factorial_block_124870_125120


private theorem factorial_join_125120_125620 : ∀ n : ℕ, 125120 ≤ n → n < 125620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_125120_125370 factorial_block_125370_125620


private theorem factorial_join_124620_125620 : ∀ n : ℕ, 124620 ≤ n → n < 125620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_124620_125120 factorial_join_125120_125620


private theorem factorial_join_123870_125620 : ∀ n : ℕ, 123870 ≤ n → n < 125620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_123870_124620 factorial_join_124620_125620


private theorem factorial_join_125620_126120 : ∀ n : ℕ, 125620 ≤ n → n < 126120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_125620_125870 factorial_block_125870_126120


private theorem factorial_join_126120_126620 : ∀ n : ℕ, 126120 ≤ n → n < 126620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_126120_126370 factorial_block_126370_126620


private theorem factorial_join_125620_126620 : ∀ n : ℕ, 125620 ≤ n → n < 126620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_125620_126120 factorial_join_126120_126620


private theorem factorial_join_126620_127120 : ∀ n : ℕ, 126620 ≤ n → n < 127120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_126620_126870 factorial_block_126870_127120


private theorem factorial_join_127120_127620 : ∀ n : ℕ, 127120 ≤ n → n < 127620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_127120_127370 factorial_block_127370_127620


private theorem factorial_join_126620_127620 : ∀ n : ℕ, 126620 ≤ n → n < 127620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_126620_127120 factorial_join_127120_127620


private theorem factorial_join_125620_127620 : ∀ n : ℕ, 125620 ≤ n → n < 127620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_125620_126620 factorial_join_126620_127620


private theorem factorial_join_123870_127620 : ∀ n : ℕ, 123870 ≤ n → n < 127620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_123870_125620 factorial_join_125620_127620


private theorem factorial_join_120120_127620 : ∀ n : ℕ, 120120 ≤ n → n < 127620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_120120_123870 factorial_join_123870_127620


private theorem factorial_join_127870_128370 : ∀ n : ℕ, 127870 ≤ n → n < 128370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_127870_128120 factorial_block_128120_128370


private theorem factorial_join_127620_128370 : ∀ n : ℕ, 127620 ≤ n → n < 128370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_127620_127870 factorial_join_127870_128370


private theorem factorial_join_128370_128870 : ∀ n : ℕ, 128370 ≤ n → n < 128870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_128370_128620 factorial_block_128620_128870


private theorem factorial_join_128870_129370 : ∀ n : ℕ, 128870 ≤ n → n < 129370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_128870_129120 factorial_block_129120_129370


private theorem factorial_join_128370_129370 : ∀ n : ℕ, 128370 ≤ n → n < 129370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_128370_128870 factorial_join_128870_129370


private theorem factorial_join_127620_129370 : ∀ n : ℕ, 127620 ≤ n → n < 129370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_127620_128370 factorial_join_128370_129370


private theorem factorial_join_129370_129870 : ∀ n : ℕ, 129370 ≤ n → n < 129870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_129370_129620 factorial_block_129620_129870


private theorem factorial_join_129870_130370 : ∀ n : ℕ, 129870 ≤ n → n < 130370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_129870_130120 factorial_block_130120_130370


private theorem factorial_join_129370_130370 : ∀ n : ℕ, 129370 ≤ n → n < 130370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_129370_129870 factorial_join_129870_130370


private theorem factorial_join_130370_130870 : ∀ n : ℕ, 130370 ≤ n → n < 130870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_130370_130620 factorial_block_130620_130870


private theorem factorial_join_130870_131370 : ∀ n : ℕ, 130870 ≤ n → n < 131370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_130870_131120 factorial_block_131120_131370


private theorem factorial_join_130370_131370 : ∀ n : ℕ, 130370 ≤ n → n < 131370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_130370_130870 factorial_join_130870_131370


private theorem factorial_join_129370_131370 : ∀ n : ℕ, 129370 ≤ n → n < 131370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_129370_130370 factorial_join_130370_131370


private theorem factorial_join_127620_131370 : ∀ n : ℕ, 127620 ≤ n → n < 131370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_127620_129370 factorial_join_129370_131370


private theorem factorial_join_131620_132120 : ∀ n : ℕ, 131620 ≤ n → n < 132120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_131620_131870 factorial_block_131870_132120


private theorem factorial_join_131370_132120 : ∀ n : ℕ, 131370 ≤ n → n < 132120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_131370_131620 factorial_join_131620_132120


private theorem factorial_join_132120_132620 : ∀ n : ℕ, 132120 ≤ n → n < 132620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_132120_132370 factorial_block_132370_132620


private theorem factorial_join_132620_133120 : ∀ n : ℕ, 132620 ≤ n → n < 133120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_132620_132870 factorial_block_132870_133120


private theorem factorial_join_132120_133120 : ∀ n : ℕ, 132120 ≤ n → n < 133120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_132120_132620 factorial_join_132620_133120


private theorem factorial_join_131370_133120 : ∀ n : ℕ, 131370 ≤ n → n < 133120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_131370_132120 factorial_join_132120_133120


private theorem factorial_join_133120_133620 : ∀ n : ℕ, 133120 ≤ n → n < 133620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_133120_133370 factorial_block_133370_133620


private theorem factorial_join_133620_134120 : ∀ n : ℕ, 133620 ≤ n → n < 134120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_133620_133870 factorial_block_133870_134120


private theorem factorial_join_133120_134120 : ∀ n : ℕ, 133120 ≤ n → n < 134120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_133120_133620 factorial_join_133620_134120


private theorem factorial_join_134120_134620 : ∀ n : ℕ, 134120 ≤ n → n < 134620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_134120_134370 factorial_block_134370_134620


private theorem factorial_join_134620_135120 : ∀ n : ℕ, 134620 ≤ n → n < 135120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_134620_134870 factorial_block_134870_135120


private theorem factorial_join_134120_135120 : ∀ n : ℕ, 134120 ≤ n → n < 135120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_134120_134620 factorial_join_134620_135120


private theorem factorial_join_133120_135120 : ∀ n : ℕ, 133120 ≤ n → n < 135120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_133120_134120 factorial_join_134120_135120


private theorem factorial_join_131370_135120 : ∀ n : ℕ, 131370 ≤ n → n < 135120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_131370_133120 factorial_join_133120_135120


private theorem factorial_join_127620_135120 : ∀ n : ℕ, 127620 ≤ n → n < 135120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_127620_131370 factorial_join_131370_135120


private theorem factorial_join_120120_135120 : ∀ n : ℕ, 120120 ≤ n → n < 135120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_120120_127620 factorial_join_127620_135120


private theorem factorial_join_135370_135870 : ∀ n : ℕ, 135370 ≤ n → n < 135870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_135370_135620 factorial_block_135620_135870


private theorem factorial_join_135120_135870 : ∀ n : ℕ, 135120 ≤ n → n < 135870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_135120_135370 factorial_join_135370_135870


private theorem factorial_join_135870_136370 : ∀ n : ℕ, 135870 ≤ n → n < 136370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_135870_136120 factorial_block_136120_136370


private theorem factorial_join_136370_136870 : ∀ n : ℕ, 136370 ≤ n → n < 136870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_136370_136620 factorial_block_136620_136870


private theorem factorial_join_135870_136870 : ∀ n : ℕ, 135870 ≤ n → n < 136870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_135870_136370 factorial_join_136370_136870


private theorem factorial_join_135120_136870 : ∀ n : ℕ, 135120 ≤ n → n < 136870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_135120_135870 factorial_join_135870_136870


private theorem factorial_join_136870_137370 : ∀ n : ℕ, 136870 ≤ n → n < 137370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_136870_137120 factorial_block_137120_137370


private theorem factorial_join_137370_137870 : ∀ n : ℕ, 137370 ≤ n → n < 137870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_137370_137620 factorial_block_137620_137870


private theorem factorial_join_136870_137870 : ∀ n : ℕ, 136870 ≤ n → n < 137870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_136870_137370 factorial_join_137370_137870


private theorem factorial_join_137870_138370 : ∀ n : ℕ, 137870 ≤ n → n < 138370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_137870_138120 factorial_block_138120_138370


private theorem factorial_join_138370_138870 : ∀ n : ℕ, 138370 ≤ n → n < 138870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_138370_138620 factorial_block_138620_138870


private theorem factorial_join_137870_138870 : ∀ n : ℕ, 137870 ≤ n → n < 138870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_137870_138370 factorial_join_138370_138870


private theorem factorial_join_136870_138870 : ∀ n : ℕ, 136870 ≤ n → n < 138870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_136870_137870 factorial_join_137870_138870


private theorem factorial_join_135120_138870 : ∀ n : ℕ, 135120 ≤ n → n < 138870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_135120_136870 factorial_join_136870_138870


private theorem factorial_join_139120_139620 : ∀ n : ℕ, 139120 ≤ n → n < 139620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_139120_139370 factorial_block_139370_139620


private theorem factorial_join_138870_139620 : ∀ n : ℕ, 138870 ≤ n → n < 139620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_138870_139120 factorial_join_139120_139620


private theorem factorial_join_139620_140120 : ∀ n : ℕ, 139620 ≤ n → n < 140120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_139620_139870 factorial_block_139870_140120


private theorem factorial_join_140120_140620 : ∀ n : ℕ, 140120 ≤ n → n < 140620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_140120_140370 factorial_block_140370_140620


private theorem factorial_join_139620_140620 : ∀ n : ℕ, 139620 ≤ n → n < 140620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_139620_140120 factorial_join_140120_140620


private theorem factorial_join_138870_140620 : ∀ n : ℕ, 138870 ≤ n → n < 140620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_138870_139620 factorial_join_139620_140620


private theorem factorial_join_140620_141120 : ∀ n : ℕ, 140620 ≤ n → n < 141120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_140620_140870 factorial_block_140870_141120


private theorem factorial_join_141120_141620 : ∀ n : ℕ, 141120 ≤ n → n < 141620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_141120_141370 factorial_block_141370_141620


private theorem factorial_join_140620_141620 : ∀ n : ℕ, 140620 ≤ n → n < 141620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_140620_141120 factorial_join_141120_141620


private theorem factorial_join_141620_142120 : ∀ n : ℕ, 141620 ≤ n → n < 142120 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_141620_141870 factorial_block_141870_142120


private theorem factorial_join_142120_142620 : ∀ n : ℕ, 142120 ≤ n → n < 142620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_142120_142370 factorial_block_142370_142620


private theorem factorial_join_141620_142620 : ∀ n : ℕ, 141620 ≤ n → n < 142620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_141620_142120 factorial_join_142120_142620


private theorem factorial_join_140620_142620 : ∀ n : ℕ, 140620 ≤ n → n < 142620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_140620_141620 factorial_join_141620_142620


private theorem factorial_join_138870_142620 : ∀ n : ℕ, 138870 ≤ n → n < 142620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_138870_140620 factorial_join_140620_142620


private theorem factorial_join_135120_142620 : ∀ n : ℕ, 135120 ≤ n → n < 142620 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_135120_138870 factorial_join_138870_142620


private theorem factorial_join_142870_143370 : ∀ n : ℕ, 142870 ≤ n → n < 143370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_142870_143120 factorial_block_143120_143370


private theorem factorial_join_142620_143370 : ∀ n : ℕ, 142620 ≤ n → n < 143370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_142620_142870 factorial_join_142870_143370


private theorem factorial_join_143370_143870 : ∀ n : ℕ, 143370 ≤ n → n < 143870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_143370_143620 factorial_block_143620_143870


private theorem factorial_join_143870_144370 : ∀ n : ℕ, 143870 ≤ n → n < 144370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_143870_144120 factorial_block_144120_144370


private theorem factorial_join_143370_144370 : ∀ n : ℕ, 143370 ≤ n → n < 144370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_143370_143870 factorial_join_143870_144370


private theorem factorial_join_142620_144370 : ∀ n : ℕ, 142620 ≤ n → n < 144370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_142620_143370 factorial_join_143370_144370


private theorem factorial_join_144370_144870 : ∀ n : ℕ, 144370 ≤ n → n < 144870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_144370_144620 factorial_block_144620_144870


private theorem factorial_join_144870_145370 : ∀ n : ℕ, 144870 ≤ n → n < 145370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_144870_145120 factorial_block_145120_145370


private theorem factorial_join_144370_145370 : ∀ n : ℕ, 144370 ≤ n → n < 145370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_144370_144870 factorial_join_144870_145370


private theorem factorial_join_145370_145870 : ∀ n : ℕ, 145370 ≤ n → n < 145870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_145370_145620 factorial_block_145620_145870


private theorem factorial_join_145870_146370 : ∀ n : ℕ, 145870 ≤ n → n < 146370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_145870_146120 factorial_block_146120_146370


private theorem factorial_join_145370_146370 : ∀ n : ℕ, 145370 ≤ n → n < 146370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_145370_145870 factorial_join_145870_146370


private theorem factorial_join_144370_146370 : ∀ n : ℕ, 144370 ≤ n → n < 146370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_144370_145370 factorial_join_145370_146370


private theorem factorial_join_142620_146370 : ∀ n : ℕ, 142620 ≤ n → n < 146370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_142620_144370 factorial_join_144370_146370


private theorem factorial_join_146370_146870 : ∀ n : ℕ, 146370 ≤ n → n < 146870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_146370_146620 factorial_block_146620_146870


private theorem factorial_join_146870_147370 : ∀ n : ℕ, 146870 ≤ n → n < 147370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_146870_147120 factorial_block_147120_147370


private theorem factorial_join_146370_147370 : ∀ n : ℕ, 146370 ≤ n → n < 147370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_146370_146870 factorial_join_146870_147370


private theorem factorial_join_147370_147870 : ∀ n : ℕ, 147370 ≤ n → n < 147870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_147370_147620 factorial_block_147620_147870


private theorem factorial_join_147870_148370 : ∀ n : ℕ, 147870 ≤ n → n < 148370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_147870_148120 factorial_block_148120_148370


private theorem factorial_join_147370_148370 : ∀ n : ℕ, 147370 ≤ n → n < 148370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_147370_147870 factorial_join_147870_148370


private theorem factorial_join_146370_148370 : ∀ n : ℕ, 146370 ≤ n → n < 148370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_146370_147370 factorial_join_147370_148370


private theorem factorial_join_148370_148870 : ∀ n : ℕ, 148370 ≤ n → n < 148870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_148370_148620 factorial_block_148620_148870


private theorem factorial_join_148870_149370 : ∀ n : ℕ, 148870 ≤ n → n < 149370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_148870_149120 factorial_block_149120_149370


private theorem factorial_join_148370_149370 : ∀ n : ℕ, 148370 ≤ n → n < 149370 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_148370_148870 factorial_join_148870_149370


private theorem factorial_join_149370_149870 : ∀ n : ℕ, 149370 ≤ n → n < 149870 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_149370_149620 factorial_block_149620_149870


private theorem factorial_join_149870_150150 : ∀ n : ℕ, 149870 ≤ n → n < 150150 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_149870_150120 factorial_block_150120_150150


private theorem factorial_join_149370_150150 : ∀ n : ℕ, 149370 ≤ n → n < 150150 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_149370_149870 factorial_join_149870_150150


private theorem factorial_join_148370_150150 : ∀ n : ℕ, 148370 ≤ n → n < 150150 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_148370_149370 factorial_join_149370_150150


private theorem factorial_join_146370_150150 : ∀ n : ℕ, 146370 ≤ n → n < 150150 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_146370_148370 factorial_join_148370_150150


private theorem factorial_join_142620_150150 : ∀ n : ℕ, 142620 ≤ n → n < 150150 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_142620_146370 factorial_join_146370_150150


private theorem factorial_join_135120_150150 : ∀ n : ℕ, 135120 ≤ n → n < 150150 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_135120_142620 factorial_join_142620_150150


/-- Certified factorial-floor range [120120, 150150). -/

theorem factorial_certificate_04 : ∀ n : ℕ, 120120 ≤ n → n < 150150 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_120120_135120 factorial_join_135120_150150


end RS12Factorial
