/-
Copyright (c) 2026 IEANTN contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Akula, PNT+ contributors
-/
import RS12.FixedCheck

/-! Generated by RS12FactorialBuildCertificate.py. Only
`factorial_certificate_10` is exported for the full-period join. -/

namespace RS12Factorial

set_option Elab.async false
set_option maxRecDepth 100000

set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_300300_300550_check : checkFixedBlock 300300 250 = true := by
  decide +kernel

private theorem factorial_block_300300_300550 : ∀ n : ℕ, 300300 ≤ n → n < 300550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_300300_300550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_300550_300800_check : checkFixedBlock 300550 250 = true := by
  decide +kernel

private theorem factorial_block_300550_300800 : ∀ n : ℕ, 300550 ≤ n → n < 300800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_300550_300800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_300800_301050_check : checkFixedBlock 300800 250 = true := by
  decide +kernel

private theorem factorial_block_300800_301050 : ∀ n : ℕ, 300800 ≤ n → n < 301050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_300800_301050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_301050_301300_check : checkFixedBlock 301050 250 = true := by
  decide +kernel

private theorem factorial_block_301050_301300 : ∀ n : ℕ, 301050 ≤ n → n < 301300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_301050_301300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_301300_301550_check : checkFixedBlock 301300 250 = true := by
  decide +kernel

private theorem factorial_block_301300_301550 : ∀ n : ℕ, 301300 ≤ n → n < 301550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_301300_301550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_301550_301800_check : checkFixedBlock 301550 250 = true := by
  decide +kernel

private theorem factorial_block_301550_301800 : ∀ n : ℕ, 301550 ≤ n → n < 301800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_301550_301800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_301800_302050_check : checkFixedBlock 301800 250 = true := by
  decide +kernel

private theorem factorial_block_301800_302050 : ∀ n : ℕ, 301800 ≤ n → n < 302050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_301800_302050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_302050_302300_check : checkFixedBlock 302050 250 = true := by
  decide +kernel

private theorem factorial_block_302050_302300 : ∀ n : ℕ, 302050 ≤ n → n < 302300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_302050_302300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_302300_302550_check : checkFixedBlock 302300 250 = true := by
  decide +kernel

private theorem factorial_block_302300_302550 : ∀ n : ℕ, 302300 ≤ n → n < 302550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_302300_302550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_302550_302800_check : checkFixedBlock 302550 250 = true := by
  decide +kernel

private theorem factorial_block_302550_302800 : ∀ n : ℕ, 302550 ≤ n → n < 302800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_302550_302800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_302800_303050_check : checkFixedBlock 302800 250 = true := by
  decide +kernel

private theorem factorial_block_302800_303050 : ∀ n : ℕ, 302800 ≤ n → n < 303050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_302800_303050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_303050_303300_check : checkFixedBlock 303050 250 = true := by
  decide +kernel

private theorem factorial_block_303050_303300 : ∀ n : ℕ, 303050 ≤ n → n < 303300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_303050_303300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_303300_303550_check : checkFixedBlock 303300 250 = true := by
  decide +kernel

private theorem factorial_block_303300_303550 : ∀ n : ℕ, 303300 ≤ n → n < 303550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_303300_303550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_303550_303800_check : checkFixedBlock 303550 250 = true := by
  decide +kernel

private theorem factorial_block_303550_303800 : ∀ n : ℕ, 303550 ≤ n → n < 303800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_303550_303800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_303800_304050_check : checkFixedBlock 303800 250 = true := by
  decide +kernel

private theorem factorial_block_303800_304050 : ∀ n : ℕ, 303800 ≤ n → n < 304050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_303800_304050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_304050_304300_check : checkFixedBlock 304050 250 = true := by
  decide +kernel

private theorem factorial_block_304050_304300 : ∀ n : ℕ, 304050 ≤ n → n < 304300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_304050_304300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_304300_304550_check : checkFixedBlock 304300 250 = true := by
  decide +kernel

private theorem factorial_block_304300_304550 : ∀ n : ℕ, 304300 ≤ n → n < 304550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_304300_304550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_304550_304800_check : checkFixedBlock 304550 250 = true := by
  decide +kernel

private theorem factorial_block_304550_304800 : ∀ n : ℕ, 304550 ≤ n → n < 304800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_304550_304800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_304800_305050_check : checkFixedBlock 304800 250 = true := by
  decide +kernel

private theorem factorial_block_304800_305050 : ∀ n : ℕ, 304800 ≤ n → n < 305050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_304800_305050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_305050_305300_check : checkFixedBlock 305050 250 = true := by
  decide +kernel

private theorem factorial_block_305050_305300 : ∀ n : ℕ, 305050 ≤ n → n < 305300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_305050_305300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_305300_305550_check : checkFixedBlock 305300 250 = true := by
  decide +kernel

private theorem factorial_block_305300_305550 : ∀ n : ℕ, 305300 ≤ n → n < 305550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_305300_305550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_305550_305800_check : checkFixedBlock 305550 250 = true := by
  decide +kernel

private theorem factorial_block_305550_305800 : ∀ n : ℕ, 305550 ≤ n → n < 305800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_305550_305800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_305800_306050_check : checkFixedBlock 305800 250 = true := by
  decide +kernel

private theorem factorial_block_305800_306050 : ∀ n : ℕ, 305800 ≤ n → n < 306050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_305800_306050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_306050_306300_check : checkFixedBlock 306050 250 = true := by
  decide +kernel

private theorem factorial_block_306050_306300 : ∀ n : ℕ, 306050 ≤ n → n < 306300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_306050_306300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_306300_306550_check : checkFixedBlock 306300 250 = true := by
  decide +kernel

private theorem factorial_block_306300_306550 : ∀ n : ℕ, 306300 ≤ n → n < 306550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_306300_306550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_306550_306800_check : checkFixedBlock 306550 250 = true := by
  decide +kernel

private theorem factorial_block_306550_306800 : ∀ n : ℕ, 306550 ≤ n → n < 306800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_306550_306800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_306800_307050_check : checkFixedBlock 306800 250 = true := by
  decide +kernel

private theorem factorial_block_306800_307050 : ∀ n : ℕ, 306800 ≤ n → n < 307050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_306800_307050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_307050_307300_check : checkFixedBlock 307050 250 = true := by
  decide +kernel

private theorem factorial_block_307050_307300 : ∀ n : ℕ, 307050 ≤ n → n < 307300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_307050_307300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_307300_307550_check : checkFixedBlock 307300 250 = true := by
  decide +kernel

private theorem factorial_block_307300_307550 : ∀ n : ℕ, 307300 ≤ n → n < 307550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_307300_307550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_307550_307800_check : checkFixedBlock 307550 250 = true := by
  decide +kernel

private theorem factorial_block_307550_307800 : ∀ n : ℕ, 307550 ≤ n → n < 307800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_307550_307800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_307800_308050_check : checkFixedBlock 307800 250 = true := by
  decide +kernel

private theorem factorial_block_307800_308050 : ∀ n : ℕ, 307800 ≤ n → n < 308050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_307800_308050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_308050_308300_check : checkFixedBlock 308050 250 = true := by
  decide +kernel

private theorem factorial_block_308050_308300 : ∀ n : ℕ, 308050 ≤ n → n < 308300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_308050_308300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_308300_308550_check : checkFixedBlock 308300 250 = true := by
  decide +kernel

private theorem factorial_block_308300_308550 : ∀ n : ℕ, 308300 ≤ n → n < 308550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_308300_308550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_308550_308800_check : checkFixedBlock 308550 250 = true := by
  decide +kernel

private theorem factorial_block_308550_308800 : ∀ n : ℕ, 308550 ≤ n → n < 308800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_308550_308800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_308800_309050_check : checkFixedBlock 308800 250 = true := by
  decide +kernel

private theorem factorial_block_308800_309050 : ∀ n : ℕ, 308800 ≤ n → n < 309050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_308800_309050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_309050_309300_check : checkFixedBlock 309050 250 = true := by
  decide +kernel

private theorem factorial_block_309050_309300 : ∀ n : ℕ, 309050 ≤ n → n < 309300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_309050_309300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_309300_309550_check : checkFixedBlock 309300 250 = true := by
  decide +kernel

private theorem factorial_block_309300_309550 : ∀ n : ℕ, 309300 ≤ n → n < 309550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_309300_309550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_309550_309800_check : checkFixedBlock 309550 250 = true := by
  decide +kernel

private theorem factorial_block_309550_309800 : ∀ n : ℕ, 309550 ≤ n → n < 309800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_309550_309800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_309800_310050_check : checkFixedBlock 309800 250 = true := by
  decide +kernel

private theorem factorial_block_309800_310050 : ∀ n : ℕ, 309800 ≤ n → n < 310050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_309800_310050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_310050_310300_check : checkFixedBlock 310050 250 = true := by
  decide +kernel

private theorem factorial_block_310050_310300 : ∀ n : ℕ, 310050 ≤ n → n < 310300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_310050_310300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_310300_310550_check : checkFixedBlock 310300 250 = true := by
  decide +kernel

private theorem factorial_block_310300_310550 : ∀ n : ℕ, 310300 ≤ n → n < 310550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_310300_310550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_310550_310800_check : checkFixedBlock 310550 250 = true := by
  decide +kernel

private theorem factorial_block_310550_310800 : ∀ n : ℕ, 310550 ≤ n → n < 310800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_310550_310800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_310800_311050_check : checkFixedBlock 310800 250 = true := by
  decide +kernel

private theorem factorial_block_310800_311050 : ∀ n : ℕ, 310800 ≤ n → n < 311050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_310800_311050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_311050_311300_check : checkFixedBlock 311050 250 = true := by
  decide +kernel

private theorem factorial_block_311050_311300 : ∀ n : ℕ, 311050 ≤ n → n < 311300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_311050_311300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_311300_311550_check : checkFixedBlock 311300 250 = true := by
  decide +kernel

private theorem factorial_block_311300_311550 : ∀ n : ℕ, 311300 ≤ n → n < 311550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_311300_311550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_311550_311800_check : checkFixedBlock 311550 250 = true := by
  decide +kernel

private theorem factorial_block_311550_311800 : ∀ n : ℕ, 311550 ≤ n → n < 311800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_311550_311800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_311800_312050_check : checkFixedBlock 311800 250 = true := by
  decide +kernel

private theorem factorial_block_311800_312050 : ∀ n : ℕ, 311800 ≤ n → n < 312050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_311800_312050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_312050_312300_check : checkFixedBlock 312050 250 = true := by
  decide +kernel

private theorem factorial_block_312050_312300 : ∀ n : ℕ, 312050 ≤ n → n < 312300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_312050_312300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_312300_312550_check : checkFixedBlock 312300 250 = true := by
  decide +kernel

private theorem factorial_block_312300_312550 : ∀ n : ℕ, 312300 ≤ n → n < 312550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_312300_312550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_312550_312800_check : checkFixedBlock 312550 250 = true := by
  decide +kernel

private theorem factorial_block_312550_312800 : ∀ n : ℕ, 312550 ≤ n → n < 312800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_312550_312800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_312800_313050_check : checkFixedBlock 312800 250 = true := by
  decide +kernel

private theorem factorial_block_312800_313050 : ∀ n : ℕ, 312800 ≤ n → n < 313050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_312800_313050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_313050_313300_check : checkFixedBlock 313050 250 = true := by
  decide +kernel

private theorem factorial_block_313050_313300 : ∀ n : ℕ, 313050 ≤ n → n < 313300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_313050_313300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_313300_313550_check : checkFixedBlock 313300 250 = true := by
  decide +kernel

private theorem factorial_block_313300_313550 : ∀ n : ℕ, 313300 ≤ n → n < 313550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_313300_313550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_313550_313800_check : checkFixedBlock 313550 250 = true := by
  decide +kernel

private theorem factorial_block_313550_313800 : ∀ n : ℕ, 313550 ≤ n → n < 313800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_313550_313800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_313800_314050_check : checkFixedBlock 313800 250 = true := by
  decide +kernel

private theorem factorial_block_313800_314050 : ∀ n : ℕ, 313800 ≤ n → n < 314050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_313800_314050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_314050_314300_check : checkFixedBlock 314050 250 = true := by
  decide +kernel

private theorem factorial_block_314050_314300 : ∀ n : ℕ, 314050 ≤ n → n < 314300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_314050_314300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_314300_314550_check : checkFixedBlock 314300 250 = true := by
  decide +kernel

private theorem factorial_block_314300_314550 : ∀ n : ℕ, 314300 ≤ n → n < 314550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_314300_314550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_314550_314800_check : checkFixedBlock 314550 250 = true := by
  decide +kernel

private theorem factorial_block_314550_314800 : ∀ n : ℕ, 314550 ≤ n → n < 314800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_314550_314800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_314800_315050_check : checkFixedBlock 314800 250 = true := by
  decide +kernel

private theorem factorial_block_314800_315050 : ∀ n : ℕ, 314800 ≤ n → n < 315050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_314800_315050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_315050_315300_check : checkFixedBlock 315050 250 = true := by
  decide +kernel

private theorem factorial_block_315050_315300 : ∀ n : ℕ, 315050 ≤ n → n < 315300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_315050_315300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_315300_315550_check : checkFixedBlock 315300 250 = true := by
  decide +kernel

private theorem factorial_block_315300_315550 : ∀ n : ℕ, 315300 ≤ n → n < 315550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_315300_315550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_315550_315800_check : checkFixedBlock 315550 250 = true := by
  decide +kernel

private theorem factorial_block_315550_315800 : ∀ n : ℕ, 315550 ≤ n → n < 315800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_315550_315800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_315800_316050_check : checkFixedBlock 315800 250 = true := by
  decide +kernel

private theorem factorial_block_315800_316050 : ∀ n : ℕ, 315800 ≤ n → n < 316050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_315800_316050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_316050_316300_check : checkFixedBlock 316050 250 = true := by
  decide +kernel

private theorem factorial_block_316050_316300 : ∀ n : ℕ, 316050 ≤ n → n < 316300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_316050_316300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_316300_316550_check : checkFixedBlock 316300 250 = true := by
  decide +kernel

private theorem factorial_block_316300_316550 : ∀ n : ℕ, 316300 ≤ n → n < 316550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_316300_316550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_316550_316800_check : checkFixedBlock 316550 250 = true := by
  decide +kernel

private theorem factorial_block_316550_316800 : ∀ n : ℕ, 316550 ≤ n → n < 316800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_316550_316800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_316800_317050_check : checkFixedBlock 316800 250 = true := by
  decide +kernel

private theorem factorial_block_316800_317050 : ∀ n : ℕ, 316800 ≤ n → n < 317050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_316800_317050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_317050_317300_check : checkFixedBlock 317050 250 = true := by
  decide +kernel

private theorem factorial_block_317050_317300 : ∀ n : ℕ, 317050 ≤ n → n < 317300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_317050_317300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_317300_317550_check : checkFixedBlock 317300 250 = true := by
  decide +kernel

private theorem factorial_block_317300_317550 : ∀ n : ℕ, 317300 ≤ n → n < 317550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_317300_317550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_317550_317800_check : checkFixedBlock 317550 250 = true := by
  decide +kernel

private theorem factorial_block_317550_317800 : ∀ n : ℕ, 317550 ≤ n → n < 317800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_317550_317800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_317800_318050_check : checkFixedBlock 317800 250 = true := by
  decide +kernel

private theorem factorial_block_317800_318050 : ∀ n : ℕ, 317800 ≤ n → n < 318050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_317800_318050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_318050_318300_check : checkFixedBlock 318050 250 = true := by
  decide +kernel

private theorem factorial_block_318050_318300 : ∀ n : ℕ, 318050 ≤ n → n < 318300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_318050_318300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_318300_318550_check : checkFixedBlock 318300 250 = true := by
  decide +kernel

private theorem factorial_block_318300_318550 : ∀ n : ℕ, 318300 ≤ n → n < 318550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_318300_318550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_318550_318800_check : checkFixedBlock 318550 250 = true := by
  decide +kernel

private theorem factorial_block_318550_318800 : ∀ n : ℕ, 318550 ≤ n → n < 318800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_318550_318800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_318800_319050_check : checkFixedBlock 318800 250 = true := by
  decide +kernel

private theorem factorial_block_318800_319050 : ∀ n : ℕ, 318800 ≤ n → n < 319050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_318800_319050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_319050_319300_check : checkFixedBlock 319050 250 = true := by
  decide +kernel

private theorem factorial_block_319050_319300 : ∀ n : ℕ, 319050 ≤ n → n < 319300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_319050_319300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_319300_319550_check : checkFixedBlock 319300 250 = true := by
  decide +kernel

private theorem factorial_block_319300_319550 : ∀ n : ℕ, 319300 ≤ n → n < 319550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_319300_319550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_319550_319800_check : checkFixedBlock 319550 250 = true := by
  decide +kernel

private theorem factorial_block_319550_319800 : ∀ n : ℕ, 319550 ≤ n → n < 319800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_319550_319800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_319800_320050_check : checkFixedBlock 319800 250 = true := by
  decide +kernel

private theorem factorial_block_319800_320050 : ∀ n : ℕ, 319800 ≤ n → n < 320050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_319800_320050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_320050_320300_check : checkFixedBlock 320050 250 = true := by
  decide +kernel

private theorem factorial_block_320050_320300 : ∀ n : ℕ, 320050 ≤ n → n < 320300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_320050_320300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_320300_320550_check : checkFixedBlock 320300 250 = true := by
  decide +kernel

private theorem factorial_block_320300_320550 : ∀ n : ℕ, 320300 ≤ n → n < 320550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_320300_320550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_320550_320800_check : checkFixedBlock 320550 250 = true := by
  decide +kernel

private theorem factorial_block_320550_320800 : ∀ n : ℕ, 320550 ≤ n → n < 320800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_320550_320800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_320800_321050_check : checkFixedBlock 320800 250 = true := by
  decide +kernel

private theorem factorial_block_320800_321050 : ∀ n : ℕ, 320800 ≤ n → n < 321050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_320800_321050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_321050_321300_check : checkFixedBlock 321050 250 = true := by
  decide +kernel

private theorem factorial_block_321050_321300 : ∀ n : ℕ, 321050 ≤ n → n < 321300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_321050_321300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_321300_321550_check : checkFixedBlock 321300 250 = true := by
  decide +kernel

private theorem factorial_block_321300_321550 : ∀ n : ℕ, 321300 ≤ n → n < 321550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_321300_321550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_321550_321800_check : checkFixedBlock 321550 250 = true := by
  decide +kernel

private theorem factorial_block_321550_321800 : ∀ n : ℕ, 321550 ≤ n → n < 321800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_321550_321800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_321800_322050_check : checkFixedBlock 321800 250 = true := by
  decide +kernel

private theorem factorial_block_321800_322050 : ∀ n : ℕ, 321800 ≤ n → n < 322050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_321800_322050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_322050_322300_check : checkFixedBlock 322050 250 = true := by
  decide +kernel

private theorem factorial_block_322050_322300 : ∀ n : ℕ, 322050 ≤ n → n < 322300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_322050_322300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_322300_322550_check : checkFixedBlock 322300 250 = true := by
  decide +kernel

private theorem factorial_block_322300_322550 : ∀ n : ℕ, 322300 ≤ n → n < 322550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_322300_322550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_322550_322800_check : checkFixedBlock 322550 250 = true := by
  decide +kernel

private theorem factorial_block_322550_322800 : ∀ n : ℕ, 322550 ≤ n → n < 322800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_322550_322800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_322800_323050_check : checkFixedBlock 322800 250 = true := by
  decide +kernel

private theorem factorial_block_322800_323050 : ∀ n : ℕ, 322800 ≤ n → n < 323050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_322800_323050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_323050_323300_check : checkFixedBlock 323050 250 = true := by
  decide +kernel

private theorem factorial_block_323050_323300 : ∀ n : ℕ, 323050 ≤ n → n < 323300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_323050_323300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_323300_323550_check : checkFixedBlock 323300 250 = true := by
  decide +kernel

private theorem factorial_block_323300_323550 : ∀ n : ℕ, 323300 ≤ n → n < 323550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_323300_323550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_323550_323800_check : checkFixedBlock 323550 250 = true := by
  decide +kernel

private theorem factorial_block_323550_323800 : ∀ n : ℕ, 323550 ≤ n → n < 323800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_323550_323800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_323800_324050_check : checkFixedBlock 323800 250 = true := by
  decide +kernel

private theorem factorial_block_323800_324050 : ∀ n : ℕ, 323800 ≤ n → n < 324050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_323800_324050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_324050_324300_check : checkFixedBlock 324050 250 = true := by
  decide +kernel

private theorem factorial_block_324050_324300 : ∀ n : ℕ, 324050 ≤ n → n < 324300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_324050_324300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_324300_324550_check : checkFixedBlock 324300 250 = true := by
  decide +kernel

private theorem factorial_block_324300_324550 : ∀ n : ℕ, 324300 ≤ n → n < 324550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_324300_324550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_324550_324800_check : checkFixedBlock 324550 250 = true := by
  decide +kernel

private theorem factorial_block_324550_324800 : ∀ n : ℕ, 324550 ≤ n → n < 324800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_324550_324800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_324800_325050_check : checkFixedBlock 324800 250 = true := by
  decide +kernel

private theorem factorial_block_324800_325050 : ∀ n : ℕ, 324800 ≤ n → n < 325050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_324800_325050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_325050_325300_check : checkFixedBlock 325050 250 = true := by
  decide +kernel

private theorem factorial_block_325050_325300 : ∀ n : ℕ, 325050 ≤ n → n < 325300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_325050_325300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_325300_325550_check : checkFixedBlock 325300 250 = true := by
  decide +kernel

private theorem factorial_block_325300_325550 : ∀ n : ℕ, 325300 ≤ n → n < 325550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_325300_325550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_325550_325800_check : checkFixedBlock 325550 250 = true := by
  decide +kernel

private theorem factorial_block_325550_325800 : ∀ n : ℕ, 325550 ≤ n → n < 325800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_325550_325800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_325800_326050_check : checkFixedBlock 325800 250 = true := by
  decide +kernel

private theorem factorial_block_325800_326050 : ∀ n : ℕ, 325800 ≤ n → n < 326050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_325800_326050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_326050_326300_check : checkFixedBlock 326050 250 = true := by
  decide +kernel

private theorem factorial_block_326050_326300 : ∀ n : ℕ, 326050 ≤ n → n < 326300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_326050_326300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_326300_326550_check : checkFixedBlock 326300 250 = true := by
  decide +kernel

private theorem factorial_block_326300_326550 : ∀ n : ℕ, 326300 ≤ n → n < 326550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_326300_326550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_326550_326800_check : checkFixedBlock 326550 250 = true := by
  decide +kernel

private theorem factorial_block_326550_326800 : ∀ n : ℕ, 326550 ≤ n → n < 326800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_326550_326800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_326800_327050_check : checkFixedBlock 326800 250 = true := by
  decide +kernel

private theorem factorial_block_326800_327050 : ∀ n : ℕ, 326800 ≤ n → n < 327050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_326800_327050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_327050_327300_check : checkFixedBlock 327050 250 = true := by
  decide +kernel

private theorem factorial_block_327050_327300 : ∀ n : ℕ, 327050 ≤ n → n < 327300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_327050_327300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_327300_327550_check : checkFixedBlock 327300 250 = true := by
  decide +kernel

private theorem factorial_block_327300_327550 : ∀ n : ℕ, 327300 ≤ n → n < 327550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_327300_327550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_327550_327800_check : checkFixedBlock 327550 250 = true := by
  decide +kernel

private theorem factorial_block_327550_327800 : ∀ n : ℕ, 327550 ≤ n → n < 327800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_327550_327800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_327800_328050_check : checkFixedBlock 327800 250 = true := by
  decide +kernel

private theorem factorial_block_327800_328050 : ∀ n : ℕ, 327800 ≤ n → n < 328050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_327800_328050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_328050_328300_check : checkFixedBlock 328050 250 = true := by
  decide +kernel

private theorem factorial_block_328050_328300 : ∀ n : ℕ, 328050 ≤ n → n < 328300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_328050_328300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_328300_328550_check : checkFixedBlock 328300 250 = true := by
  decide +kernel

private theorem factorial_block_328300_328550 : ∀ n : ℕ, 328300 ≤ n → n < 328550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_328300_328550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_328550_328800_check : checkFixedBlock 328550 250 = true := by
  decide +kernel

private theorem factorial_block_328550_328800 : ∀ n : ℕ, 328550 ≤ n → n < 328800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_328550_328800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_328800_329050_check : checkFixedBlock 328800 250 = true := by
  decide +kernel

private theorem factorial_block_328800_329050 : ∀ n : ℕ, 328800 ≤ n → n < 329050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_328800_329050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_329050_329300_check : checkFixedBlock 329050 250 = true := by
  decide +kernel

private theorem factorial_block_329050_329300 : ∀ n : ℕ, 329050 ≤ n → n < 329300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_329050_329300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_329300_329550_check : checkFixedBlock 329300 250 = true := by
  decide +kernel

private theorem factorial_block_329300_329550 : ∀ n : ℕ, 329300 ≤ n → n < 329550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_329300_329550_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_329550_329800_check : checkFixedBlock 329550 250 = true := by
  decide +kernel

private theorem factorial_block_329550_329800 : ∀ n : ℕ, 329550 ≤ n → n < 329800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_329550_329800_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_329800_330050_check : checkFixedBlock 329800 250 = true := by
  decide +kernel

private theorem factorial_block_329800_330050 : ∀ n : ℕ, 329800 ≤ n → n < 330050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_329800_330050_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_330050_330300_check : checkFixedBlock 330050 250 = true := by
  decide +kernel

private theorem factorial_block_330050_330300 : ∀ n : ℕ, 330050 ≤ n → n < 330300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_330050_330300_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_330300_330330_check : checkFixedBlock 330300 30 = true := by
  decide +kernel

private theorem factorial_block_330300_330330 : ∀ n : ℕ, 330300 ≤ n → n < 330330 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_330300_330330_check hlo hhi


private theorem factorial_join_300550_301050 : ∀ n : ℕ, 300550 ≤ n → n < 301050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_300550_300800 factorial_block_300800_301050


private theorem factorial_join_300300_301050 : ∀ n : ℕ, 300300 ≤ n → n < 301050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_300300_300550 factorial_join_300550_301050


private theorem factorial_join_301050_301550 : ∀ n : ℕ, 301050 ≤ n → n < 301550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_301050_301300 factorial_block_301300_301550


private theorem factorial_join_301550_302050 : ∀ n : ℕ, 301550 ≤ n → n < 302050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_301550_301800 factorial_block_301800_302050


private theorem factorial_join_301050_302050 : ∀ n : ℕ, 301050 ≤ n → n < 302050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_301050_301550 factorial_join_301550_302050


private theorem factorial_join_300300_302050 : ∀ n : ℕ, 300300 ≤ n → n < 302050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_300300_301050 factorial_join_301050_302050


private theorem factorial_join_302050_302550 : ∀ n : ℕ, 302050 ≤ n → n < 302550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_302050_302300 factorial_block_302300_302550


private theorem factorial_join_302550_303050 : ∀ n : ℕ, 302550 ≤ n → n < 303050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_302550_302800 factorial_block_302800_303050


private theorem factorial_join_302050_303050 : ∀ n : ℕ, 302050 ≤ n → n < 303050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_302050_302550 factorial_join_302550_303050


private theorem factorial_join_303050_303550 : ∀ n : ℕ, 303050 ≤ n → n < 303550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_303050_303300 factorial_block_303300_303550


private theorem factorial_join_303550_304050 : ∀ n : ℕ, 303550 ≤ n → n < 304050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_303550_303800 factorial_block_303800_304050


private theorem factorial_join_303050_304050 : ∀ n : ℕ, 303050 ≤ n → n < 304050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_303050_303550 factorial_join_303550_304050


private theorem factorial_join_302050_304050 : ∀ n : ℕ, 302050 ≤ n → n < 304050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_302050_303050 factorial_join_303050_304050


private theorem factorial_join_300300_304050 : ∀ n : ℕ, 300300 ≤ n → n < 304050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_300300_302050 factorial_join_302050_304050


private theorem factorial_join_304300_304800 : ∀ n : ℕ, 304300 ≤ n → n < 304800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_304300_304550 factorial_block_304550_304800


private theorem factorial_join_304050_304800 : ∀ n : ℕ, 304050 ≤ n → n < 304800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_304050_304300 factorial_join_304300_304800


private theorem factorial_join_304800_305300 : ∀ n : ℕ, 304800 ≤ n → n < 305300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_304800_305050 factorial_block_305050_305300


private theorem factorial_join_305300_305800 : ∀ n : ℕ, 305300 ≤ n → n < 305800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_305300_305550 factorial_block_305550_305800


private theorem factorial_join_304800_305800 : ∀ n : ℕ, 304800 ≤ n → n < 305800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_304800_305300 factorial_join_305300_305800


private theorem factorial_join_304050_305800 : ∀ n : ℕ, 304050 ≤ n → n < 305800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_304050_304800 factorial_join_304800_305800


private theorem factorial_join_305800_306300 : ∀ n : ℕ, 305800 ≤ n → n < 306300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_305800_306050 factorial_block_306050_306300


private theorem factorial_join_306300_306800 : ∀ n : ℕ, 306300 ≤ n → n < 306800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_306300_306550 factorial_block_306550_306800


private theorem factorial_join_305800_306800 : ∀ n : ℕ, 305800 ≤ n → n < 306800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_305800_306300 factorial_join_306300_306800


private theorem factorial_join_306800_307300 : ∀ n : ℕ, 306800 ≤ n → n < 307300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_306800_307050 factorial_block_307050_307300


private theorem factorial_join_307300_307800 : ∀ n : ℕ, 307300 ≤ n → n < 307800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_307300_307550 factorial_block_307550_307800


private theorem factorial_join_306800_307800 : ∀ n : ℕ, 306800 ≤ n → n < 307800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_306800_307300 factorial_join_307300_307800


private theorem factorial_join_305800_307800 : ∀ n : ℕ, 305800 ≤ n → n < 307800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_305800_306800 factorial_join_306800_307800


private theorem factorial_join_304050_307800 : ∀ n : ℕ, 304050 ≤ n → n < 307800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_304050_305800 factorial_join_305800_307800


private theorem factorial_join_300300_307800 : ∀ n : ℕ, 300300 ≤ n → n < 307800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_300300_304050 factorial_join_304050_307800


private theorem factorial_join_308050_308550 : ∀ n : ℕ, 308050 ≤ n → n < 308550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_308050_308300 factorial_block_308300_308550


private theorem factorial_join_307800_308550 : ∀ n : ℕ, 307800 ≤ n → n < 308550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_307800_308050 factorial_join_308050_308550


private theorem factorial_join_308550_309050 : ∀ n : ℕ, 308550 ≤ n → n < 309050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_308550_308800 factorial_block_308800_309050


private theorem factorial_join_309050_309550 : ∀ n : ℕ, 309050 ≤ n → n < 309550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_309050_309300 factorial_block_309300_309550


private theorem factorial_join_308550_309550 : ∀ n : ℕ, 308550 ≤ n → n < 309550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_308550_309050 factorial_join_309050_309550


private theorem factorial_join_307800_309550 : ∀ n : ℕ, 307800 ≤ n → n < 309550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_307800_308550 factorial_join_308550_309550


private theorem factorial_join_309550_310050 : ∀ n : ℕ, 309550 ≤ n → n < 310050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_309550_309800 factorial_block_309800_310050


private theorem factorial_join_310050_310550 : ∀ n : ℕ, 310050 ≤ n → n < 310550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_310050_310300 factorial_block_310300_310550


private theorem factorial_join_309550_310550 : ∀ n : ℕ, 309550 ≤ n → n < 310550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_309550_310050 factorial_join_310050_310550


private theorem factorial_join_310550_311050 : ∀ n : ℕ, 310550 ≤ n → n < 311050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_310550_310800 factorial_block_310800_311050


private theorem factorial_join_311050_311550 : ∀ n : ℕ, 311050 ≤ n → n < 311550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_311050_311300 factorial_block_311300_311550


private theorem factorial_join_310550_311550 : ∀ n : ℕ, 310550 ≤ n → n < 311550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_310550_311050 factorial_join_311050_311550


private theorem factorial_join_309550_311550 : ∀ n : ℕ, 309550 ≤ n → n < 311550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_309550_310550 factorial_join_310550_311550


private theorem factorial_join_307800_311550 : ∀ n : ℕ, 307800 ≤ n → n < 311550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_307800_309550 factorial_join_309550_311550


private theorem factorial_join_311800_312300 : ∀ n : ℕ, 311800 ≤ n → n < 312300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_311800_312050 factorial_block_312050_312300


private theorem factorial_join_311550_312300 : ∀ n : ℕ, 311550 ≤ n → n < 312300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_311550_311800 factorial_join_311800_312300


private theorem factorial_join_312300_312800 : ∀ n : ℕ, 312300 ≤ n → n < 312800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_312300_312550 factorial_block_312550_312800


private theorem factorial_join_312800_313300 : ∀ n : ℕ, 312800 ≤ n → n < 313300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_312800_313050 factorial_block_313050_313300


private theorem factorial_join_312300_313300 : ∀ n : ℕ, 312300 ≤ n → n < 313300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_312300_312800 factorial_join_312800_313300


private theorem factorial_join_311550_313300 : ∀ n : ℕ, 311550 ≤ n → n < 313300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_311550_312300 factorial_join_312300_313300


private theorem factorial_join_313300_313800 : ∀ n : ℕ, 313300 ≤ n → n < 313800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_313300_313550 factorial_block_313550_313800


private theorem factorial_join_313800_314300 : ∀ n : ℕ, 313800 ≤ n → n < 314300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_313800_314050 factorial_block_314050_314300


private theorem factorial_join_313300_314300 : ∀ n : ℕ, 313300 ≤ n → n < 314300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_313300_313800 factorial_join_313800_314300


private theorem factorial_join_314300_314800 : ∀ n : ℕ, 314300 ≤ n → n < 314800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_314300_314550 factorial_block_314550_314800


private theorem factorial_join_314800_315300 : ∀ n : ℕ, 314800 ≤ n → n < 315300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_314800_315050 factorial_block_315050_315300


private theorem factorial_join_314300_315300 : ∀ n : ℕ, 314300 ≤ n → n < 315300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_314300_314800 factorial_join_314800_315300


private theorem factorial_join_313300_315300 : ∀ n : ℕ, 313300 ≤ n → n < 315300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_313300_314300 factorial_join_314300_315300


private theorem factorial_join_311550_315300 : ∀ n : ℕ, 311550 ≤ n → n < 315300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_311550_313300 factorial_join_313300_315300


private theorem factorial_join_307800_315300 : ∀ n : ℕ, 307800 ≤ n → n < 315300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_307800_311550 factorial_join_311550_315300


private theorem factorial_join_300300_315300 : ∀ n : ℕ, 300300 ≤ n → n < 315300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_300300_307800 factorial_join_307800_315300


private theorem factorial_join_315550_316050 : ∀ n : ℕ, 315550 ≤ n → n < 316050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_315550_315800 factorial_block_315800_316050


private theorem factorial_join_315300_316050 : ∀ n : ℕ, 315300 ≤ n → n < 316050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_315300_315550 factorial_join_315550_316050


private theorem factorial_join_316050_316550 : ∀ n : ℕ, 316050 ≤ n → n < 316550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_316050_316300 factorial_block_316300_316550


private theorem factorial_join_316550_317050 : ∀ n : ℕ, 316550 ≤ n → n < 317050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_316550_316800 factorial_block_316800_317050


private theorem factorial_join_316050_317050 : ∀ n : ℕ, 316050 ≤ n → n < 317050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_316050_316550 factorial_join_316550_317050


private theorem factorial_join_315300_317050 : ∀ n : ℕ, 315300 ≤ n → n < 317050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_315300_316050 factorial_join_316050_317050


private theorem factorial_join_317050_317550 : ∀ n : ℕ, 317050 ≤ n → n < 317550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_317050_317300 factorial_block_317300_317550


private theorem factorial_join_317550_318050 : ∀ n : ℕ, 317550 ≤ n → n < 318050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_317550_317800 factorial_block_317800_318050


private theorem factorial_join_317050_318050 : ∀ n : ℕ, 317050 ≤ n → n < 318050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_317050_317550 factorial_join_317550_318050


private theorem factorial_join_318050_318550 : ∀ n : ℕ, 318050 ≤ n → n < 318550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_318050_318300 factorial_block_318300_318550


private theorem factorial_join_318550_319050 : ∀ n : ℕ, 318550 ≤ n → n < 319050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_318550_318800 factorial_block_318800_319050


private theorem factorial_join_318050_319050 : ∀ n : ℕ, 318050 ≤ n → n < 319050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_318050_318550 factorial_join_318550_319050


private theorem factorial_join_317050_319050 : ∀ n : ℕ, 317050 ≤ n → n < 319050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_317050_318050 factorial_join_318050_319050


private theorem factorial_join_315300_319050 : ∀ n : ℕ, 315300 ≤ n → n < 319050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_315300_317050 factorial_join_317050_319050


private theorem factorial_join_319300_319800 : ∀ n : ℕ, 319300 ≤ n → n < 319800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_319300_319550 factorial_block_319550_319800


private theorem factorial_join_319050_319800 : ∀ n : ℕ, 319050 ≤ n → n < 319800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_319050_319300 factorial_join_319300_319800


private theorem factorial_join_319800_320300 : ∀ n : ℕ, 319800 ≤ n → n < 320300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_319800_320050 factorial_block_320050_320300


private theorem factorial_join_320300_320800 : ∀ n : ℕ, 320300 ≤ n → n < 320800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_320300_320550 factorial_block_320550_320800


private theorem factorial_join_319800_320800 : ∀ n : ℕ, 319800 ≤ n → n < 320800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_319800_320300 factorial_join_320300_320800


private theorem factorial_join_319050_320800 : ∀ n : ℕ, 319050 ≤ n → n < 320800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_319050_319800 factorial_join_319800_320800


private theorem factorial_join_320800_321300 : ∀ n : ℕ, 320800 ≤ n → n < 321300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_320800_321050 factorial_block_321050_321300


private theorem factorial_join_321300_321800 : ∀ n : ℕ, 321300 ≤ n → n < 321800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_321300_321550 factorial_block_321550_321800


private theorem factorial_join_320800_321800 : ∀ n : ℕ, 320800 ≤ n → n < 321800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_320800_321300 factorial_join_321300_321800


private theorem factorial_join_321800_322300 : ∀ n : ℕ, 321800 ≤ n → n < 322300 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_321800_322050 factorial_block_322050_322300


private theorem factorial_join_322300_322800 : ∀ n : ℕ, 322300 ≤ n → n < 322800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_322300_322550 factorial_block_322550_322800


private theorem factorial_join_321800_322800 : ∀ n : ℕ, 321800 ≤ n → n < 322800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_321800_322300 factorial_join_322300_322800


private theorem factorial_join_320800_322800 : ∀ n : ℕ, 320800 ≤ n → n < 322800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_320800_321800 factorial_join_321800_322800


private theorem factorial_join_319050_322800 : ∀ n : ℕ, 319050 ≤ n → n < 322800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_319050_320800 factorial_join_320800_322800


private theorem factorial_join_315300_322800 : ∀ n : ℕ, 315300 ≤ n → n < 322800 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_315300_319050 factorial_join_319050_322800


private theorem factorial_join_323050_323550 : ∀ n : ℕ, 323050 ≤ n → n < 323550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_323050_323300 factorial_block_323300_323550


private theorem factorial_join_322800_323550 : ∀ n : ℕ, 322800 ≤ n → n < 323550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_322800_323050 factorial_join_323050_323550


private theorem factorial_join_323550_324050 : ∀ n : ℕ, 323550 ≤ n → n < 324050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_323550_323800 factorial_block_323800_324050


private theorem factorial_join_324050_324550 : ∀ n : ℕ, 324050 ≤ n → n < 324550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_324050_324300 factorial_block_324300_324550


private theorem factorial_join_323550_324550 : ∀ n : ℕ, 323550 ≤ n → n < 324550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_323550_324050 factorial_join_324050_324550


private theorem factorial_join_322800_324550 : ∀ n : ℕ, 322800 ≤ n → n < 324550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_322800_323550 factorial_join_323550_324550


private theorem factorial_join_324550_325050 : ∀ n : ℕ, 324550 ≤ n → n < 325050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_324550_324800 factorial_block_324800_325050


private theorem factorial_join_325050_325550 : ∀ n : ℕ, 325050 ≤ n → n < 325550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_325050_325300 factorial_block_325300_325550


private theorem factorial_join_324550_325550 : ∀ n : ℕ, 324550 ≤ n → n < 325550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_324550_325050 factorial_join_325050_325550


private theorem factorial_join_325550_326050 : ∀ n : ℕ, 325550 ≤ n → n < 326050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_325550_325800 factorial_block_325800_326050


private theorem factorial_join_326050_326550 : ∀ n : ℕ, 326050 ≤ n → n < 326550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_326050_326300 factorial_block_326300_326550


private theorem factorial_join_325550_326550 : ∀ n : ℕ, 325550 ≤ n → n < 326550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_325550_326050 factorial_join_326050_326550


private theorem factorial_join_324550_326550 : ∀ n : ℕ, 324550 ≤ n → n < 326550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_324550_325550 factorial_join_325550_326550


private theorem factorial_join_322800_326550 : ∀ n : ℕ, 322800 ≤ n → n < 326550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_322800_324550 factorial_join_324550_326550


private theorem factorial_join_326550_327050 : ∀ n : ℕ, 326550 ≤ n → n < 327050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_326550_326800 factorial_block_326800_327050


private theorem factorial_join_327050_327550 : ∀ n : ℕ, 327050 ≤ n → n < 327550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_327050_327300 factorial_block_327300_327550


private theorem factorial_join_326550_327550 : ∀ n : ℕ, 326550 ≤ n → n < 327550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_326550_327050 factorial_join_327050_327550


private theorem factorial_join_327550_328050 : ∀ n : ℕ, 327550 ≤ n → n < 328050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_327550_327800 factorial_block_327800_328050


private theorem factorial_join_328050_328550 : ∀ n : ℕ, 328050 ≤ n → n < 328550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_328050_328300 factorial_block_328300_328550


private theorem factorial_join_327550_328550 : ∀ n : ℕ, 327550 ≤ n → n < 328550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_327550_328050 factorial_join_328050_328550


private theorem factorial_join_326550_328550 : ∀ n : ℕ, 326550 ≤ n → n < 328550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_326550_327550 factorial_join_327550_328550


private theorem factorial_join_328550_329050 : ∀ n : ℕ, 328550 ≤ n → n < 329050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_328550_328800 factorial_block_328800_329050


private theorem factorial_join_329050_329550 : ∀ n : ℕ, 329050 ≤ n → n < 329550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_329050_329300 factorial_block_329300_329550


private theorem factorial_join_328550_329550 : ∀ n : ℕ, 328550 ≤ n → n < 329550 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_328550_329050 factorial_join_329050_329550


private theorem factorial_join_329550_330050 : ∀ n : ℕ, 329550 ≤ n → n < 330050 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_329550_329800 factorial_block_329800_330050


private theorem factorial_join_330050_330330 : ∀ n : ℕ, 330050 ≤ n → n < 330330 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_330050_330300 factorial_block_330300_330330


private theorem factorial_join_329550_330330 : ∀ n : ℕ, 329550 ≤ n → n < 330330 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_329550_330050 factorial_join_330050_330330


private theorem factorial_join_328550_330330 : ∀ n : ℕ, 328550 ≤ n → n < 330330 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_328550_329550 factorial_join_329550_330330


private theorem factorial_join_326550_330330 : ∀ n : ℕ, 326550 ≤ n → n < 330330 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_326550_328550 factorial_join_328550_330330


private theorem factorial_join_322800_330330 : ∀ n : ℕ, 322800 ≤ n → n < 330330 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_322800_326550 factorial_join_326550_330330


private theorem factorial_join_315300_330330 : ∀ n : ℕ, 315300 ≤ n → n < 330330 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_315300_322800 factorial_join_322800_330330


/-- Certified factorial-floor range [300300, 330330). -/

theorem factorial_certificate_10 : ∀ n : ℕ, 300300 ≤ n → n < 330330 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_300300_315300 factorial_join_315300_330330


end RS12Factorial
