/-
Copyright (c) 2026 IEANTN contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Akula, PNT+ contributors
-/
import RS12.FixedCheck

/-! Generated by RS12FactorialBuildCertificate.py. Only
`factorial_certificate_07` is exported for the full-period join. -/

namespace RS12Factorial

set_option Elab.async false
set_option maxRecDepth 100000

set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_210210_210460_check : checkFixedBlock 210210 250 = true := by
  decide +kernel

private theorem factorial_block_210210_210460 : ∀ n : ℕ, 210210 ≤ n → n < 210460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_210210_210460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_210460_210710_check : checkFixedBlock 210460 250 = true := by
  decide +kernel

private theorem factorial_block_210460_210710 : ∀ n : ℕ, 210460 ≤ n → n < 210710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_210460_210710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_210710_210960_check : checkFixedBlock 210710 250 = true := by
  decide +kernel

private theorem factorial_block_210710_210960 : ∀ n : ℕ, 210710 ≤ n → n < 210960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_210710_210960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_210960_211210_check : checkFixedBlock 210960 250 = true := by
  decide +kernel

private theorem factorial_block_210960_211210 : ∀ n : ℕ, 210960 ≤ n → n < 211210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_210960_211210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_211210_211460_check : checkFixedBlock 211210 250 = true := by
  decide +kernel

private theorem factorial_block_211210_211460 : ∀ n : ℕ, 211210 ≤ n → n < 211460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_211210_211460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_211460_211710_check : checkFixedBlock 211460 250 = true := by
  decide +kernel

private theorem factorial_block_211460_211710 : ∀ n : ℕ, 211460 ≤ n → n < 211710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_211460_211710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_211710_211960_check : checkFixedBlock 211710 250 = true := by
  decide +kernel

private theorem factorial_block_211710_211960 : ∀ n : ℕ, 211710 ≤ n → n < 211960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_211710_211960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_211960_212210_check : checkFixedBlock 211960 250 = true := by
  decide +kernel

private theorem factorial_block_211960_212210 : ∀ n : ℕ, 211960 ≤ n → n < 212210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_211960_212210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_212210_212460_check : checkFixedBlock 212210 250 = true := by
  decide +kernel

private theorem factorial_block_212210_212460 : ∀ n : ℕ, 212210 ≤ n → n < 212460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_212210_212460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_212460_212710_check : checkFixedBlock 212460 250 = true := by
  decide +kernel

private theorem factorial_block_212460_212710 : ∀ n : ℕ, 212460 ≤ n → n < 212710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_212460_212710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_212710_212960_check : checkFixedBlock 212710 250 = true := by
  decide +kernel

private theorem factorial_block_212710_212960 : ∀ n : ℕ, 212710 ≤ n → n < 212960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_212710_212960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_212960_213210_check : checkFixedBlock 212960 250 = true := by
  decide +kernel

private theorem factorial_block_212960_213210 : ∀ n : ℕ, 212960 ≤ n → n < 213210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_212960_213210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_213210_213460_check : checkFixedBlock 213210 250 = true := by
  decide +kernel

private theorem factorial_block_213210_213460 : ∀ n : ℕ, 213210 ≤ n → n < 213460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_213210_213460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_213460_213710_check : checkFixedBlock 213460 250 = true := by
  decide +kernel

private theorem factorial_block_213460_213710 : ∀ n : ℕ, 213460 ≤ n → n < 213710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_213460_213710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_213710_213960_check : checkFixedBlock 213710 250 = true := by
  decide +kernel

private theorem factorial_block_213710_213960 : ∀ n : ℕ, 213710 ≤ n → n < 213960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_213710_213960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_213960_214210_check : checkFixedBlock 213960 250 = true := by
  decide +kernel

private theorem factorial_block_213960_214210 : ∀ n : ℕ, 213960 ≤ n → n < 214210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_213960_214210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_214210_214460_check : checkFixedBlock 214210 250 = true := by
  decide +kernel

private theorem factorial_block_214210_214460 : ∀ n : ℕ, 214210 ≤ n → n < 214460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_214210_214460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_214460_214710_check : checkFixedBlock 214460 250 = true := by
  decide +kernel

private theorem factorial_block_214460_214710 : ∀ n : ℕ, 214460 ≤ n → n < 214710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_214460_214710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_214710_214960_check : checkFixedBlock 214710 250 = true := by
  decide +kernel

private theorem factorial_block_214710_214960 : ∀ n : ℕ, 214710 ≤ n → n < 214960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_214710_214960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_214960_215210_check : checkFixedBlock 214960 250 = true := by
  decide +kernel

private theorem factorial_block_214960_215210 : ∀ n : ℕ, 214960 ≤ n → n < 215210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_214960_215210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_215210_215460_check : checkFixedBlock 215210 250 = true := by
  decide +kernel

private theorem factorial_block_215210_215460 : ∀ n : ℕ, 215210 ≤ n → n < 215460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_215210_215460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_215460_215710_check : checkFixedBlock 215460 250 = true := by
  decide +kernel

private theorem factorial_block_215460_215710 : ∀ n : ℕ, 215460 ≤ n → n < 215710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_215460_215710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_215710_215960_check : checkFixedBlock 215710 250 = true := by
  decide +kernel

private theorem factorial_block_215710_215960 : ∀ n : ℕ, 215710 ≤ n → n < 215960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_215710_215960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_215960_216210_check : checkFixedBlock 215960 250 = true := by
  decide +kernel

private theorem factorial_block_215960_216210 : ∀ n : ℕ, 215960 ≤ n → n < 216210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_215960_216210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_216210_216460_check : checkFixedBlock 216210 250 = true := by
  decide +kernel

private theorem factorial_block_216210_216460 : ∀ n : ℕ, 216210 ≤ n → n < 216460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_216210_216460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_216460_216710_check : checkFixedBlock 216460 250 = true := by
  decide +kernel

private theorem factorial_block_216460_216710 : ∀ n : ℕ, 216460 ≤ n → n < 216710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_216460_216710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_216710_216960_check : checkFixedBlock 216710 250 = true := by
  decide +kernel

private theorem factorial_block_216710_216960 : ∀ n : ℕ, 216710 ≤ n → n < 216960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_216710_216960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_216960_217210_check : checkFixedBlock 216960 250 = true := by
  decide +kernel

private theorem factorial_block_216960_217210 : ∀ n : ℕ, 216960 ≤ n → n < 217210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_216960_217210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_217210_217460_check : checkFixedBlock 217210 250 = true := by
  decide +kernel

private theorem factorial_block_217210_217460 : ∀ n : ℕ, 217210 ≤ n → n < 217460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_217210_217460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_217460_217710_check : checkFixedBlock 217460 250 = true := by
  decide +kernel

private theorem factorial_block_217460_217710 : ∀ n : ℕ, 217460 ≤ n → n < 217710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_217460_217710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_217710_217960_check : checkFixedBlock 217710 250 = true := by
  decide +kernel

private theorem factorial_block_217710_217960 : ∀ n : ℕ, 217710 ≤ n → n < 217960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_217710_217960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_217960_218210_check : checkFixedBlock 217960 250 = true := by
  decide +kernel

private theorem factorial_block_217960_218210 : ∀ n : ℕ, 217960 ≤ n → n < 218210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_217960_218210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_218210_218460_check : checkFixedBlock 218210 250 = true := by
  decide +kernel

private theorem factorial_block_218210_218460 : ∀ n : ℕ, 218210 ≤ n → n < 218460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_218210_218460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_218460_218710_check : checkFixedBlock 218460 250 = true := by
  decide +kernel

private theorem factorial_block_218460_218710 : ∀ n : ℕ, 218460 ≤ n → n < 218710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_218460_218710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_218710_218960_check : checkFixedBlock 218710 250 = true := by
  decide +kernel

private theorem factorial_block_218710_218960 : ∀ n : ℕ, 218710 ≤ n → n < 218960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_218710_218960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_218960_219210_check : checkFixedBlock 218960 250 = true := by
  decide +kernel

private theorem factorial_block_218960_219210 : ∀ n : ℕ, 218960 ≤ n → n < 219210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_218960_219210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_219210_219460_check : checkFixedBlock 219210 250 = true := by
  decide +kernel

private theorem factorial_block_219210_219460 : ∀ n : ℕ, 219210 ≤ n → n < 219460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_219210_219460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_219460_219710_check : checkFixedBlock 219460 250 = true := by
  decide +kernel

private theorem factorial_block_219460_219710 : ∀ n : ℕ, 219460 ≤ n → n < 219710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_219460_219710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_219710_219960_check : checkFixedBlock 219710 250 = true := by
  decide +kernel

private theorem factorial_block_219710_219960 : ∀ n : ℕ, 219710 ≤ n → n < 219960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_219710_219960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_219960_220210_check : checkFixedBlock 219960 250 = true := by
  decide +kernel

private theorem factorial_block_219960_220210 : ∀ n : ℕ, 219960 ≤ n → n < 220210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_219960_220210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_220210_220460_check : checkFixedBlock 220210 250 = true := by
  decide +kernel

private theorem factorial_block_220210_220460 : ∀ n : ℕ, 220210 ≤ n → n < 220460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_220210_220460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_220460_220710_check : checkFixedBlock 220460 250 = true := by
  decide +kernel

private theorem factorial_block_220460_220710 : ∀ n : ℕ, 220460 ≤ n → n < 220710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_220460_220710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_220710_220960_check : checkFixedBlock 220710 250 = true := by
  decide +kernel

private theorem factorial_block_220710_220960 : ∀ n : ℕ, 220710 ≤ n → n < 220960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_220710_220960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_220960_221210_check : checkFixedBlock 220960 250 = true := by
  decide +kernel

private theorem factorial_block_220960_221210 : ∀ n : ℕ, 220960 ≤ n → n < 221210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_220960_221210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_221210_221460_check : checkFixedBlock 221210 250 = true := by
  decide +kernel

private theorem factorial_block_221210_221460 : ∀ n : ℕ, 221210 ≤ n → n < 221460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_221210_221460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_221460_221710_check : checkFixedBlock 221460 250 = true := by
  decide +kernel

private theorem factorial_block_221460_221710 : ∀ n : ℕ, 221460 ≤ n → n < 221710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_221460_221710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_221710_221960_check : checkFixedBlock 221710 250 = true := by
  decide +kernel

private theorem factorial_block_221710_221960 : ∀ n : ℕ, 221710 ≤ n → n < 221960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_221710_221960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_221960_222210_check : checkFixedBlock 221960 250 = true := by
  decide +kernel

private theorem factorial_block_221960_222210 : ∀ n : ℕ, 221960 ≤ n → n < 222210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_221960_222210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_222210_222460_check : checkFixedBlock 222210 250 = true := by
  decide +kernel

private theorem factorial_block_222210_222460 : ∀ n : ℕ, 222210 ≤ n → n < 222460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_222210_222460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_222460_222710_check : checkFixedBlock 222460 250 = true := by
  decide +kernel

private theorem factorial_block_222460_222710 : ∀ n : ℕ, 222460 ≤ n → n < 222710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_222460_222710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_222710_222960_check : checkFixedBlock 222710 250 = true := by
  decide +kernel

private theorem factorial_block_222710_222960 : ∀ n : ℕ, 222710 ≤ n → n < 222960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_222710_222960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_222960_223210_check : checkFixedBlock 222960 250 = true := by
  decide +kernel

private theorem factorial_block_222960_223210 : ∀ n : ℕ, 222960 ≤ n → n < 223210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_222960_223210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_223210_223460_check : checkFixedBlock 223210 250 = true := by
  decide +kernel

private theorem factorial_block_223210_223460 : ∀ n : ℕ, 223210 ≤ n → n < 223460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_223210_223460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_223460_223710_check : checkFixedBlock 223460 250 = true := by
  decide +kernel

private theorem factorial_block_223460_223710 : ∀ n : ℕ, 223460 ≤ n → n < 223710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_223460_223710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_223710_223960_check : checkFixedBlock 223710 250 = true := by
  decide +kernel

private theorem factorial_block_223710_223960 : ∀ n : ℕ, 223710 ≤ n → n < 223960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_223710_223960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_223960_224210_check : checkFixedBlock 223960 250 = true := by
  decide +kernel

private theorem factorial_block_223960_224210 : ∀ n : ℕ, 223960 ≤ n → n < 224210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_223960_224210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_224210_224460_check : checkFixedBlock 224210 250 = true := by
  decide +kernel

private theorem factorial_block_224210_224460 : ∀ n : ℕ, 224210 ≤ n → n < 224460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_224210_224460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_224460_224710_check : checkFixedBlock 224460 250 = true := by
  decide +kernel

private theorem factorial_block_224460_224710 : ∀ n : ℕ, 224460 ≤ n → n < 224710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_224460_224710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_224710_224960_check : checkFixedBlock 224710 250 = true := by
  decide +kernel

private theorem factorial_block_224710_224960 : ∀ n : ℕ, 224710 ≤ n → n < 224960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_224710_224960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_224960_225210_check : checkFixedBlock 224960 250 = true := by
  decide +kernel

private theorem factorial_block_224960_225210 : ∀ n : ℕ, 224960 ≤ n → n < 225210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_224960_225210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_225210_225460_check : checkFixedBlock 225210 250 = true := by
  decide +kernel

private theorem factorial_block_225210_225460 : ∀ n : ℕ, 225210 ≤ n → n < 225460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_225210_225460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_225460_225710_check : checkFixedBlock 225460 250 = true := by
  decide +kernel

private theorem factorial_block_225460_225710 : ∀ n : ℕ, 225460 ≤ n → n < 225710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_225460_225710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_225710_225960_check : checkFixedBlock 225710 250 = true := by
  decide +kernel

private theorem factorial_block_225710_225960 : ∀ n : ℕ, 225710 ≤ n → n < 225960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_225710_225960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_225960_226210_check : checkFixedBlock 225960 250 = true := by
  decide +kernel

private theorem factorial_block_225960_226210 : ∀ n : ℕ, 225960 ≤ n → n < 226210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_225960_226210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_226210_226460_check : checkFixedBlock 226210 250 = true := by
  decide +kernel

private theorem factorial_block_226210_226460 : ∀ n : ℕ, 226210 ≤ n → n < 226460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_226210_226460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_226460_226710_check : checkFixedBlock 226460 250 = true := by
  decide +kernel

private theorem factorial_block_226460_226710 : ∀ n : ℕ, 226460 ≤ n → n < 226710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_226460_226710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_226710_226960_check : checkFixedBlock 226710 250 = true := by
  decide +kernel

private theorem factorial_block_226710_226960 : ∀ n : ℕ, 226710 ≤ n → n < 226960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_226710_226960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_226960_227210_check : checkFixedBlock 226960 250 = true := by
  decide +kernel

private theorem factorial_block_226960_227210 : ∀ n : ℕ, 226960 ≤ n → n < 227210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_226960_227210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_227210_227460_check : checkFixedBlock 227210 250 = true := by
  decide +kernel

private theorem factorial_block_227210_227460 : ∀ n : ℕ, 227210 ≤ n → n < 227460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_227210_227460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_227460_227710_check : checkFixedBlock 227460 250 = true := by
  decide +kernel

private theorem factorial_block_227460_227710 : ∀ n : ℕ, 227460 ≤ n → n < 227710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_227460_227710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_227710_227960_check : checkFixedBlock 227710 250 = true := by
  decide +kernel

private theorem factorial_block_227710_227960 : ∀ n : ℕ, 227710 ≤ n → n < 227960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_227710_227960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_227960_228210_check : checkFixedBlock 227960 250 = true := by
  decide +kernel

private theorem factorial_block_227960_228210 : ∀ n : ℕ, 227960 ≤ n → n < 228210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_227960_228210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_228210_228460_check : checkFixedBlock 228210 250 = true := by
  decide +kernel

private theorem factorial_block_228210_228460 : ∀ n : ℕ, 228210 ≤ n → n < 228460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_228210_228460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_228460_228710_check : checkFixedBlock 228460 250 = true := by
  decide +kernel

private theorem factorial_block_228460_228710 : ∀ n : ℕ, 228460 ≤ n → n < 228710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_228460_228710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_228710_228960_check : checkFixedBlock 228710 250 = true := by
  decide +kernel

private theorem factorial_block_228710_228960 : ∀ n : ℕ, 228710 ≤ n → n < 228960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_228710_228960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_228960_229210_check : checkFixedBlock 228960 250 = true := by
  decide +kernel

private theorem factorial_block_228960_229210 : ∀ n : ℕ, 228960 ≤ n → n < 229210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_228960_229210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_229210_229460_check : checkFixedBlock 229210 250 = true := by
  decide +kernel

private theorem factorial_block_229210_229460 : ∀ n : ℕ, 229210 ≤ n → n < 229460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_229210_229460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_229460_229710_check : checkFixedBlock 229460 250 = true := by
  decide +kernel

private theorem factorial_block_229460_229710 : ∀ n : ℕ, 229460 ≤ n → n < 229710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_229460_229710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_229710_229960_check : checkFixedBlock 229710 250 = true := by
  decide +kernel

private theorem factorial_block_229710_229960 : ∀ n : ℕ, 229710 ≤ n → n < 229960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_229710_229960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_229960_230210_check : checkFixedBlock 229960 250 = true := by
  decide +kernel

private theorem factorial_block_229960_230210 : ∀ n : ℕ, 229960 ≤ n → n < 230210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_229960_230210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_230210_230460_check : checkFixedBlock 230210 250 = true := by
  decide +kernel

private theorem factorial_block_230210_230460 : ∀ n : ℕ, 230210 ≤ n → n < 230460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_230210_230460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_230460_230710_check : checkFixedBlock 230460 250 = true := by
  decide +kernel

private theorem factorial_block_230460_230710 : ∀ n : ℕ, 230460 ≤ n → n < 230710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_230460_230710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_230710_230960_check : checkFixedBlock 230710 250 = true := by
  decide +kernel

private theorem factorial_block_230710_230960 : ∀ n : ℕ, 230710 ≤ n → n < 230960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_230710_230960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_230960_231210_check : checkFixedBlock 230960 250 = true := by
  decide +kernel

private theorem factorial_block_230960_231210 : ∀ n : ℕ, 230960 ≤ n → n < 231210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_230960_231210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_231210_231460_check : checkFixedBlock 231210 250 = true := by
  decide +kernel

private theorem factorial_block_231210_231460 : ∀ n : ℕ, 231210 ≤ n → n < 231460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_231210_231460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_231460_231710_check : checkFixedBlock 231460 250 = true := by
  decide +kernel

private theorem factorial_block_231460_231710 : ∀ n : ℕ, 231460 ≤ n → n < 231710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_231460_231710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_231710_231960_check : checkFixedBlock 231710 250 = true := by
  decide +kernel

private theorem factorial_block_231710_231960 : ∀ n : ℕ, 231710 ≤ n → n < 231960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_231710_231960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_231960_232210_check : checkFixedBlock 231960 250 = true := by
  decide +kernel

private theorem factorial_block_231960_232210 : ∀ n : ℕ, 231960 ≤ n → n < 232210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_231960_232210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_232210_232460_check : checkFixedBlock 232210 250 = true := by
  decide +kernel

private theorem factorial_block_232210_232460 : ∀ n : ℕ, 232210 ≤ n → n < 232460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_232210_232460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_232460_232710_check : checkFixedBlock 232460 250 = true := by
  decide +kernel

private theorem factorial_block_232460_232710 : ∀ n : ℕ, 232460 ≤ n → n < 232710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_232460_232710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_232710_232960_check : checkFixedBlock 232710 250 = true := by
  decide +kernel

private theorem factorial_block_232710_232960 : ∀ n : ℕ, 232710 ≤ n → n < 232960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_232710_232960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_232960_233210_check : checkFixedBlock 232960 250 = true := by
  decide +kernel

private theorem factorial_block_232960_233210 : ∀ n : ℕ, 232960 ≤ n → n < 233210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_232960_233210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_233210_233460_check : checkFixedBlock 233210 250 = true := by
  decide +kernel

private theorem factorial_block_233210_233460 : ∀ n : ℕ, 233210 ≤ n → n < 233460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_233210_233460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_233460_233710_check : checkFixedBlock 233460 250 = true := by
  decide +kernel

private theorem factorial_block_233460_233710 : ∀ n : ℕ, 233460 ≤ n → n < 233710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_233460_233710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_233710_233960_check : checkFixedBlock 233710 250 = true := by
  decide +kernel

private theorem factorial_block_233710_233960 : ∀ n : ℕ, 233710 ≤ n → n < 233960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_233710_233960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_233960_234210_check : checkFixedBlock 233960 250 = true := by
  decide +kernel

private theorem factorial_block_233960_234210 : ∀ n : ℕ, 233960 ≤ n → n < 234210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_233960_234210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_234210_234460_check : checkFixedBlock 234210 250 = true := by
  decide +kernel

private theorem factorial_block_234210_234460 : ∀ n : ℕ, 234210 ≤ n → n < 234460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_234210_234460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_234460_234710_check : checkFixedBlock 234460 250 = true := by
  decide +kernel

private theorem factorial_block_234460_234710 : ∀ n : ℕ, 234460 ≤ n → n < 234710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_234460_234710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_234710_234960_check : checkFixedBlock 234710 250 = true := by
  decide +kernel

private theorem factorial_block_234710_234960 : ∀ n : ℕ, 234710 ≤ n → n < 234960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_234710_234960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_234960_235210_check : checkFixedBlock 234960 250 = true := by
  decide +kernel

private theorem factorial_block_234960_235210 : ∀ n : ℕ, 234960 ≤ n → n < 235210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_234960_235210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_235210_235460_check : checkFixedBlock 235210 250 = true := by
  decide +kernel

private theorem factorial_block_235210_235460 : ∀ n : ℕ, 235210 ≤ n → n < 235460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_235210_235460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_235460_235710_check : checkFixedBlock 235460 250 = true := by
  decide +kernel

private theorem factorial_block_235460_235710 : ∀ n : ℕ, 235460 ≤ n → n < 235710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_235460_235710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_235710_235960_check : checkFixedBlock 235710 250 = true := by
  decide +kernel

private theorem factorial_block_235710_235960 : ∀ n : ℕ, 235710 ≤ n → n < 235960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_235710_235960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_235960_236210_check : checkFixedBlock 235960 250 = true := by
  decide +kernel

private theorem factorial_block_235960_236210 : ∀ n : ℕ, 235960 ≤ n → n < 236210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_235960_236210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_236210_236460_check : checkFixedBlock 236210 250 = true := by
  decide +kernel

private theorem factorial_block_236210_236460 : ∀ n : ℕ, 236210 ≤ n → n < 236460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_236210_236460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_236460_236710_check : checkFixedBlock 236460 250 = true := by
  decide +kernel

private theorem factorial_block_236460_236710 : ∀ n : ℕ, 236460 ≤ n → n < 236710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_236460_236710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_236710_236960_check : checkFixedBlock 236710 250 = true := by
  decide +kernel

private theorem factorial_block_236710_236960 : ∀ n : ℕ, 236710 ≤ n → n < 236960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_236710_236960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_236960_237210_check : checkFixedBlock 236960 250 = true := by
  decide +kernel

private theorem factorial_block_236960_237210 : ∀ n : ℕ, 236960 ≤ n → n < 237210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_236960_237210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_237210_237460_check : checkFixedBlock 237210 250 = true := by
  decide +kernel

private theorem factorial_block_237210_237460 : ∀ n : ℕ, 237210 ≤ n → n < 237460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_237210_237460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_237460_237710_check : checkFixedBlock 237460 250 = true := by
  decide +kernel

private theorem factorial_block_237460_237710 : ∀ n : ℕ, 237460 ≤ n → n < 237710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_237460_237710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_237710_237960_check : checkFixedBlock 237710 250 = true := by
  decide +kernel

private theorem factorial_block_237710_237960 : ∀ n : ℕ, 237710 ≤ n → n < 237960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_237710_237960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_237960_238210_check : checkFixedBlock 237960 250 = true := by
  decide +kernel

private theorem factorial_block_237960_238210 : ∀ n : ℕ, 237960 ≤ n → n < 238210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_237960_238210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_238210_238460_check : checkFixedBlock 238210 250 = true := by
  decide +kernel

private theorem factorial_block_238210_238460 : ∀ n : ℕ, 238210 ≤ n → n < 238460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_238210_238460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_238460_238710_check : checkFixedBlock 238460 250 = true := by
  decide +kernel

private theorem factorial_block_238460_238710 : ∀ n : ℕ, 238460 ≤ n → n < 238710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_238460_238710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_238710_238960_check : checkFixedBlock 238710 250 = true := by
  decide +kernel

private theorem factorial_block_238710_238960 : ∀ n : ℕ, 238710 ≤ n → n < 238960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_238710_238960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_238960_239210_check : checkFixedBlock 238960 250 = true := by
  decide +kernel

private theorem factorial_block_238960_239210 : ∀ n : ℕ, 238960 ≤ n → n < 239210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_238960_239210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_239210_239460_check : checkFixedBlock 239210 250 = true := by
  decide +kernel

private theorem factorial_block_239210_239460 : ∀ n : ℕ, 239210 ≤ n → n < 239460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_239210_239460_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_239460_239710_check : checkFixedBlock 239460 250 = true := by
  decide +kernel

private theorem factorial_block_239460_239710 : ∀ n : ℕ, 239460 ≤ n → n < 239710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_239460_239710_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_239710_239960_check : checkFixedBlock 239710 250 = true := by
  decide +kernel

private theorem factorial_block_239710_239960 : ∀ n : ℕ, 239710 ≤ n → n < 239960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_239710_239960_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_239960_240210_check : checkFixedBlock 239960 250 = true := by
  decide +kernel

private theorem factorial_block_239960_240210 : ∀ n : ℕ, 239960 ≤ n → n < 240210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_239960_240210_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_240210_240240_check : checkFixedBlock 240210 30 = true := by
  decide +kernel

private theorem factorial_block_240210_240240 : ∀ n : ℕ, 240210 ≤ n → n < 240240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_240210_240240_check hlo hhi


private theorem factorial_join_210460_210960 : ∀ n : ℕ, 210460 ≤ n → n < 210960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_210460_210710 factorial_block_210710_210960


private theorem factorial_join_210210_210960 : ∀ n : ℕ, 210210 ≤ n → n < 210960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_210210_210460 factorial_join_210460_210960


private theorem factorial_join_210960_211460 : ∀ n : ℕ, 210960 ≤ n → n < 211460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_210960_211210 factorial_block_211210_211460


private theorem factorial_join_211460_211960 : ∀ n : ℕ, 211460 ≤ n → n < 211960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_211460_211710 factorial_block_211710_211960


private theorem factorial_join_210960_211960 : ∀ n : ℕ, 210960 ≤ n → n < 211960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_210960_211460 factorial_join_211460_211960


private theorem factorial_join_210210_211960 : ∀ n : ℕ, 210210 ≤ n → n < 211960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_210210_210960 factorial_join_210960_211960


private theorem factorial_join_211960_212460 : ∀ n : ℕ, 211960 ≤ n → n < 212460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_211960_212210 factorial_block_212210_212460


private theorem factorial_join_212460_212960 : ∀ n : ℕ, 212460 ≤ n → n < 212960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_212460_212710 factorial_block_212710_212960


private theorem factorial_join_211960_212960 : ∀ n : ℕ, 211960 ≤ n → n < 212960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_211960_212460 factorial_join_212460_212960


private theorem factorial_join_212960_213460 : ∀ n : ℕ, 212960 ≤ n → n < 213460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_212960_213210 factorial_block_213210_213460


private theorem factorial_join_213460_213960 : ∀ n : ℕ, 213460 ≤ n → n < 213960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_213460_213710 factorial_block_213710_213960


private theorem factorial_join_212960_213960 : ∀ n : ℕ, 212960 ≤ n → n < 213960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_212960_213460 factorial_join_213460_213960


private theorem factorial_join_211960_213960 : ∀ n : ℕ, 211960 ≤ n → n < 213960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_211960_212960 factorial_join_212960_213960


private theorem factorial_join_210210_213960 : ∀ n : ℕ, 210210 ≤ n → n < 213960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_210210_211960 factorial_join_211960_213960


private theorem factorial_join_214210_214710 : ∀ n : ℕ, 214210 ≤ n → n < 214710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_214210_214460 factorial_block_214460_214710


private theorem factorial_join_213960_214710 : ∀ n : ℕ, 213960 ≤ n → n < 214710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_213960_214210 factorial_join_214210_214710


private theorem factorial_join_214710_215210 : ∀ n : ℕ, 214710 ≤ n → n < 215210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_214710_214960 factorial_block_214960_215210


private theorem factorial_join_215210_215710 : ∀ n : ℕ, 215210 ≤ n → n < 215710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_215210_215460 factorial_block_215460_215710


private theorem factorial_join_214710_215710 : ∀ n : ℕ, 214710 ≤ n → n < 215710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_214710_215210 factorial_join_215210_215710


private theorem factorial_join_213960_215710 : ∀ n : ℕ, 213960 ≤ n → n < 215710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_213960_214710 factorial_join_214710_215710


private theorem factorial_join_215710_216210 : ∀ n : ℕ, 215710 ≤ n → n < 216210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_215710_215960 factorial_block_215960_216210


private theorem factorial_join_216210_216710 : ∀ n : ℕ, 216210 ≤ n → n < 216710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_216210_216460 factorial_block_216460_216710


private theorem factorial_join_215710_216710 : ∀ n : ℕ, 215710 ≤ n → n < 216710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_215710_216210 factorial_join_216210_216710


private theorem factorial_join_216710_217210 : ∀ n : ℕ, 216710 ≤ n → n < 217210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_216710_216960 factorial_block_216960_217210


private theorem factorial_join_217210_217710 : ∀ n : ℕ, 217210 ≤ n → n < 217710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_217210_217460 factorial_block_217460_217710


private theorem factorial_join_216710_217710 : ∀ n : ℕ, 216710 ≤ n → n < 217710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_216710_217210 factorial_join_217210_217710


private theorem factorial_join_215710_217710 : ∀ n : ℕ, 215710 ≤ n → n < 217710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_215710_216710 factorial_join_216710_217710


private theorem factorial_join_213960_217710 : ∀ n : ℕ, 213960 ≤ n → n < 217710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_213960_215710 factorial_join_215710_217710


private theorem factorial_join_210210_217710 : ∀ n : ℕ, 210210 ≤ n → n < 217710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_210210_213960 factorial_join_213960_217710


private theorem factorial_join_217960_218460 : ∀ n : ℕ, 217960 ≤ n → n < 218460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_217960_218210 factorial_block_218210_218460


private theorem factorial_join_217710_218460 : ∀ n : ℕ, 217710 ≤ n → n < 218460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_217710_217960 factorial_join_217960_218460


private theorem factorial_join_218460_218960 : ∀ n : ℕ, 218460 ≤ n → n < 218960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_218460_218710 factorial_block_218710_218960


private theorem factorial_join_218960_219460 : ∀ n : ℕ, 218960 ≤ n → n < 219460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_218960_219210 factorial_block_219210_219460


private theorem factorial_join_218460_219460 : ∀ n : ℕ, 218460 ≤ n → n < 219460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_218460_218960 factorial_join_218960_219460


private theorem factorial_join_217710_219460 : ∀ n : ℕ, 217710 ≤ n → n < 219460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_217710_218460 factorial_join_218460_219460


private theorem factorial_join_219460_219960 : ∀ n : ℕ, 219460 ≤ n → n < 219960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_219460_219710 factorial_block_219710_219960


private theorem factorial_join_219960_220460 : ∀ n : ℕ, 219960 ≤ n → n < 220460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_219960_220210 factorial_block_220210_220460


private theorem factorial_join_219460_220460 : ∀ n : ℕ, 219460 ≤ n → n < 220460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_219460_219960 factorial_join_219960_220460


private theorem factorial_join_220460_220960 : ∀ n : ℕ, 220460 ≤ n → n < 220960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_220460_220710 factorial_block_220710_220960


private theorem factorial_join_220960_221460 : ∀ n : ℕ, 220960 ≤ n → n < 221460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_220960_221210 factorial_block_221210_221460


private theorem factorial_join_220460_221460 : ∀ n : ℕ, 220460 ≤ n → n < 221460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_220460_220960 factorial_join_220960_221460


private theorem factorial_join_219460_221460 : ∀ n : ℕ, 219460 ≤ n → n < 221460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_219460_220460 factorial_join_220460_221460


private theorem factorial_join_217710_221460 : ∀ n : ℕ, 217710 ≤ n → n < 221460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_217710_219460 factorial_join_219460_221460


private theorem factorial_join_221710_222210 : ∀ n : ℕ, 221710 ≤ n → n < 222210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_221710_221960 factorial_block_221960_222210


private theorem factorial_join_221460_222210 : ∀ n : ℕ, 221460 ≤ n → n < 222210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_221460_221710 factorial_join_221710_222210


private theorem factorial_join_222210_222710 : ∀ n : ℕ, 222210 ≤ n → n < 222710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_222210_222460 factorial_block_222460_222710


private theorem factorial_join_222710_223210 : ∀ n : ℕ, 222710 ≤ n → n < 223210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_222710_222960 factorial_block_222960_223210


private theorem factorial_join_222210_223210 : ∀ n : ℕ, 222210 ≤ n → n < 223210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_222210_222710 factorial_join_222710_223210


private theorem factorial_join_221460_223210 : ∀ n : ℕ, 221460 ≤ n → n < 223210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_221460_222210 factorial_join_222210_223210


private theorem factorial_join_223210_223710 : ∀ n : ℕ, 223210 ≤ n → n < 223710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_223210_223460 factorial_block_223460_223710


private theorem factorial_join_223710_224210 : ∀ n : ℕ, 223710 ≤ n → n < 224210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_223710_223960 factorial_block_223960_224210


private theorem factorial_join_223210_224210 : ∀ n : ℕ, 223210 ≤ n → n < 224210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_223210_223710 factorial_join_223710_224210


private theorem factorial_join_224210_224710 : ∀ n : ℕ, 224210 ≤ n → n < 224710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_224210_224460 factorial_block_224460_224710


private theorem factorial_join_224710_225210 : ∀ n : ℕ, 224710 ≤ n → n < 225210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_224710_224960 factorial_block_224960_225210


private theorem factorial_join_224210_225210 : ∀ n : ℕ, 224210 ≤ n → n < 225210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_224210_224710 factorial_join_224710_225210


private theorem factorial_join_223210_225210 : ∀ n : ℕ, 223210 ≤ n → n < 225210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_223210_224210 factorial_join_224210_225210


private theorem factorial_join_221460_225210 : ∀ n : ℕ, 221460 ≤ n → n < 225210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_221460_223210 factorial_join_223210_225210


private theorem factorial_join_217710_225210 : ∀ n : ℕ, 217710 ≤ n → n < 225210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_217710_221460 factorial_join_221460_225210


private theorem factorial_join_210210_225210 : ∀ n : ℕ, 210210 ≤ n → n < 225210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_210210_217710 factorial_join_217710_225210


private theorem factorial_join_225460_225960 : ∀ n : ℕ, 225460 ≤ n → n < 225960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_225460_225710 factorial_block_225710_225960


private theorem factorial_join_225210_225960 : ∀ n : ℕ, 225210 ≤ n → n < 225960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_225210_225460 factorial_join_225460_225960


private theorem factorial_join_225960_226460 : ∀ n : ℕ, 225960 ≤ n → n < 226460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_225960_226210 factorial_block_226210_226460


private theorem factorial_join_226460_226960 : ∀ n : ℕ, 226460 ≤ n → n < 226960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_226460_226710 factorial_block_226710_226960


private theorem factorial_join_225960_226960 : ∀ n : ℕ, 225960 ≤ n → n < 226960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_225960_226460 factorial_join_226460_226960


private theorem factorial_join_225210_226960 : ∀ n : ℕ, 225210 ≤ n → n < 226960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_225210_225960 factorial_join_225960_226960


private theorem factorial_join_226960_227460 : ∀ n : ℕ, 226960 ≤ n → n < 227460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_226960_227210 factorial_block_227210_227460


private theorem factorial_join_227460_227960 : ∀ n : ℕ, 227460 ≤ n → n < 227960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_227460_227710 factorial_block_227710_227960


private theorem factorial_join_226960_227960 : ∀ n : ℕ, 226960 ≤ n → n < 227960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_226960_227460 factorial_join_227460_227960


private theorem factorial_join_227960_228460 : ∀ n : ℕ, 227960 ≤ n → n < 228460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_227960_228210 factorial_block_228210_228460


private theorem factorial_join_228460_228960 : ∀ n : ℕ, 228460 ≤ n → n < 228960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_228460_228710 factorial_block_228710_228960


private theorem factorial_join_227960_228960 : ∀ n : ℕ, 227960 ≤ n → n < 228960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_227960_228460 factorial_join_228460_228960


private theorem factorial_join_226960_228960 : ∀ n : ℕ, 226960 ≤ n → n < 228960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_226960_227960 factorial_join_227960_228960


private theorem factorial_join_225210_228960 : ∀ n : ℕ, 225210 ≤ n → n < 228960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_225210_226960 factorial_join_226960_228960


private theorem factorial_join_229210_229710 : ∀ n : ℕ, 229210 ≤ n → n < 229710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_229210_229460 factorial_block_229460_229710


private theorem factorial_join_228960_229710 : ∀ n : ℕ, 228960 ≤ n → n < 229710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_228960_229210 factorial_join_229210_229710


private theorem factorial_join_229710_230210 : ∀ n : ℕ, 229710 ≤ n → n < 230210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_229710_229960 factorial_block_229960_230210


private theorem factorial_join_230210_230710 : ∀ n : ℕ, 230210 ≤ n → n < 230710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_230210_230460 factorial_block_230460_230710


private theorem factorial_join_229710_230710 : ∀ n : ℕ, 229710 ≤ n → n < 230710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_229710_230210 factorial_join_230210_230710


private theorem factorial_join_228960_230710 : ∀ n : ℕ, 228960 ≤ n → n < 230710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_228960_229710 factorial_join_229710_230710


private theorem factorial_join_230710_231210 : ∀ n : ℕ, 230710 ≤ n → n < 231210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_230710_230960 factorial_block_230960_231210


private theorem factorial_join_231210_231710 : ∀ n : ℕ, 231210 ≤ n → n < 231710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_231210_231460 factorial_block_231460_231710


private theorem factorial_join_230710_231710 : ∀ n : ℕ, 230710 ≤ n → n < 231710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_230710_231210 factorial_join_231210_231710


private theorem factorial_join_231710_232210 : ∀ n : ℕ, 231710 ≤ n → n < 232210 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_231710_231960 factorial_block_231960_232210


private theorem factorial_join_232210_232710 : ∀ n : ℕ, 232210 ≤ n → n < 232710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_232210_232460 factorial_block_232460_232710


private theorem factorial_join_231710_232710 : ∀ n : ℕ, 231710 ≤ n → n < 232710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_231710_232210 factorial_join_232210_232710


private theorem factorial_join_230710_232710 : ∀ n : ℕ, 230710 ≤ n → n < 232710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_230710_231710 factorial_join_231710_232710


private theorem factorial_join_228960_232710 : ∀ n : ℕ, 228960 ≤ n → n < 232710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_228960_230710 factorial_join_230710_232710


private theorem factorial_join_225210_232710 : ∀ n : ℕ, 225210 ≤ n → n < 232710 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_225210_228960 factorial_join_228960_232710


private theorem factorial_join_232960_233460 : ∀ n : ℕ, 232960 ≤ n → n < 233460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_232960_233210 factorial_block_233210_233460


private theorem factorial_join_232710_233460 : ∀ n : ℕ, 232710 ≤ n → n < 233460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_232710_232960 factorial_join_232960_233460


private theorem factorial_join_233460_233960 : ∀ n : ℕ, 233460 ≤ n → n < 233960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_233460_233710 factorial_block_233710_233960


private theorem factorial_join_233960_234460 : ∀ n : ℕ, 233960 ≤ n → n < 234460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_233960_234210 factorial_block_234210_234460


private theorem factorial_join_233460_234460 : ∀ n : ℕ, 233460 ≤ n → n < 234460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_233460_233960 factorial_join_233960_234460


private theorem factorial_join_232710_234460 : ∀ n : ℕ, 232710 ≤ n → n < 234460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_232710_233460 factorial_join_233460_234460


private theorem factorial_join_234460_234960 : ∀ n : ℕ, 234460 ≤ n → n < 234960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_234460_234710 factorial_block_234710_234960


private theorem factorial_join_234960_235460 : ∀ n : ℕ, 234960 ≤ n → n < 235460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_234960_235210 factorial_block_235210_235460


private theorem factorial_join_234460_235460 : ∀ n : ℕ, 234460 ≤ n → n < 235460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_234460_234960 factorial_join_234960_235460


private theorem factorial_join_235460_235960 : ∀ n : ℕ, 235460 ≤ n → n < 235960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_235460_235710 factorial_block_235710_235960


private theorem factorial_join_235960_236460 : ∀ n : ℕ, 235960 ≤ n → n < 236460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_235960_236210 factorial_block_236210_236460


private theorem factorial_join_235460_236460 : ∀ n : ℕ, 235460 ≤ n → n < 236460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_235460_235960 factorial_join_235960_236460


private theorem factorial_join_234460_236460 : ∀ n : ℕ, 234460 ≤ n → n < 236460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_234460_235460 factorial_join_235460_236460


private theorem factorial_join_232710_236460 : ∀ n : ℕ, 232710 ≤ n → n < 236460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_232710_234460 factorial_join_234460_236460


private theorem factorial_join_236460_236960 : ∀ n : ℕ, 236460 ≤ n → n < 236960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_236460_236710 factorial_block_236710_236960


private theorem factorial_join_236960_237460 : ∀ n : ℕ, 236960 ≤ n → n < 237460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_236960_237210 factorial_block_237210_237460


private theorem factorial_join_236460_237460 : ∀ n : ℕ, 236460 ≤ n → n < 237460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_236460_236960 factorial_join_236960_237460


private theorem factorial_join_237460_237960 : ∀ n : ℕ, 237460 ≤ n → n < 237960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_237460_237710 factorial_block_237710_237960


private theorem factorial_join_237960_238460 : ∀ n : ℕ, 237960 ≤ n → n < 238460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_237960_238210 factorial_block_238210_238460


private theorem factorial_join_237460_238460 : ∀ n : ℕ, 237460 ≤ n → n < 238460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_237460_237960 factorial_join_237960_238460


private theorem factorial_join_236460_238460 : ∀ n : ℕ, 236460 ≤ n → n < 238460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_236460_237460 factorial_join_237460_238460


private theorem factorial_join_238460_238960 : ∀ n : ℕ, 238460 ≤ n → n < 238960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_238460_238710 factorial_block_238710_238960


private theorem factorial_join_238960_239460 : ∀ n : ℕ, 238960 ≤ n → n < 239460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_238960_239210 factorial_block_239210_239460


private theorem factorial_join_238460_239460 : ∀ n : ℕ, 238460 ≤ n → n < 239460 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_238460_238960 factorial_join_238960_239460


private theorem factorial_join_239460_239960 : ∀ n : ℕ, 239460 ≤ n → n < 239960 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_239460_239710 factorial_block_239710_239960


private theorem factorial_join_239960_240240 : ∀ n : ℕ, 239960 ≤ n → n < 240240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_239960_240210 factorial_block_240210_240240


private theorem factorial_join_239460_240240 : ∀ n : ℕ, 239460 ≤ n → n < 240240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_239460_239960 factorial_join_239960_240240


private theorem factorial_join_238460_240240 : ∀ n : ℕ, 238460 ≤ n → n < 240240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_238460_239460 factorial_join_239460_240240


private theorem factorial_join_236460_240240 : ∀ n : ℕ, 236460 ≤ n → n < 240240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_236460_238460 factorial_join_238460_240240


private theorem factorial_join_232710_240240 : ∀ n : ℕ, 232710 ≤ n → n < 240240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_232710_236460 factorial_join_236460_240240


private theorem factorial_join_225210_240240 : ∀ n : ℕ, 225210 ≤ n → n < 240240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_225210_232710 factorial_join_232710_240240


/-- Certified factorial-floor range [210210, 240240). -/

theorem factorial_certificate_07 : ∀ n : ℕ, 210210 ≤ n → n < 240240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_210210_225210 factorial_join_225210_240240


end RS12Factorial
