/-
Copyright (c) 2026 IEANTN contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Akula, PNT+ contributors
-/
import RS12.FixedCheck

/-! Generated by RS12FactorialBuildCertificate.py. Only
`factorial_certificate_08` is exported for the full-period join. -/

namespace RS12Factorial

set_option Elab.async false
set_option maxRecDepth 100000

set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_240240_240490_check : checkFixedBlock 240240 250 = true := by
  decide +kernel

private theorem factorial_block_240240_240490 : ∀ n : ℕ, 240240 ≤ n → n < 240490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_240240_240490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_240490_240740_check : checkFixedBlock 240490 250 = true := by
  decide +kernel

private theorem factorial_block_240490_240740 : ∀ n : ℕ, 240490 ≤ n → n < 240740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_240490_240740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_240740_240990_check : checkFixedBlock 240740 250 = true := by
  decide +kernel

private theorem factorial_block_240740_240990 : ∀ n : ℕ, 240740 ≤ n → n < 240990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_240740_240990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_240990_241240_check : checkFixedBlock 240990 250 = true := by
  decide +kernel

private theorem factorial_block_240990_241240 : ∀ n : ℕ, 240990 ≤ n → n < 241240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_240990_241240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_241240_241490_check : checkFixedBlock 241240 250 = true := by
  decide +kernel

private theorem factorial_block_241240_241490 : ∀ n : ℕ, 241240 ≤ n → n < 241490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_241240_241490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_241490_241740_check : checkFixedBlock 241490 250 = true := by
  decide +kernel

private theorem factorial_block_241490_241740 : ∀ n : ℕ, 241490 ≤ n → n < 241740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_241490_241740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_241740_241990_check : checkFixedBlock 241740 250 = true := by
  decide +kernel

private theorem factorial_block_241740_241990 : ∀ n : ℕ, 241740 ≤ n → n < 241990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_241740_241990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_241990_242240_check : checkFixedBlock 241990 250 = true := by
  decide +kernel

private theorem factorial_block_241990_242240 : ∀ n : ℕ, 241990 ≤ n → n < 242240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_241990_242240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_242240_242490_check : checkFixedBlock 242240 250 = true := by
  decide +kernel

private theorem factorial_block_242240_242490 : ∀ n : ℕ, 242240 ≤ n → n < 242490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_242240_242490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_242490_242740_check : checkFixedBlock 242490 250 = true := by
  decide +kernel

private theorem factorial_block_242490_242740 : ∀ n : ℕ, 242490 ≤ n → n < 242740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_242490_242740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_242740_242990_check : checkFixedBlock 242740 250 = true := by
  decide +kernel

private theorem factorial_block_242740_242990 : ∀ n : ℕ, 242740 ≤ n → n < 242990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_242740_242990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_242990_243240_check : checkFixedBlock 242990 250 = true := by
  decide +kernel

private theorem factorial_block_242990_243240 : ∀ n : ℕ, 242990 ≤ n → n < 243240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_242990_243240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_243240_243490_check : checkFixedBlock 243240 250 = true := by
  decide +kernel

private theorem factorial_block_243240_243490 : ∀ n : ℕ, 243240 ≤ n → n < 243490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_243240_243490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_243490_243740_check : checkFixedBlock 243490 250 = true := by
  decide +kernel

private theorem factorial_block_243490_243740 : ∀ n : ℕ, 243490 ≤ n → n < 243740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_243490_243740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_243740_243990_check : checkFixedBlock 243740 250 = true := by
  decide +kernel

private theorem factorial_block_243740_243990 : ∀ n : ℕ, 243740 ≤ n → n < 243990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_243740_243990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_243990_244240_check : checkFixedBlock 243990 250 = true := by
  decide +kernel

private theorem factorial_block_243990_244240 : ∀ n : ℕ, 243990 ≤ n → n < 244240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_243990_244240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_244240_244490_check : checkFixedBlock 244240 250 = true := by
  decide +kernel

private theorem factorial_block_244240_244490 : ∀ n : ℕ, 244240 ≤ n → n < 244490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_244240_244490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_244490_244740_check : checkFixedBlock 244490 250 = true := by
  decide +kernel

private theorem factorial_block_244490_244740 : ∀ n : ℕ, 244490 ≤ n → n < 244740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_244490_244740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_244740_244990_check : checkFixedBlock 244740 250 = true := by
  decide +kernel

private theorem factorial_block_244740_244990 : ∀ n : ℕ, 244740 ≤ n → n < 244990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_244740_244990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_244990_245240_check : checkFixedBlock 244990 250 = true := by
  decide +kernel

private theorem factorial_block_244990_245240 : ∀ n : ℕ, 244990 ≤ n → n < 245240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_244990_245240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_245240_245490_check : checkFixedBlock 245240 250 = true := by
  decide +kernel

private theorem factorial_block_245240_245490 : ∀ n : ℕ, 245240 ≤ n → n < 245490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_245240_245490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_245490_245740_check : checkFixedBlock 245490 250 = true := by
  decide +kernel

private theorem factorial_block_245490_245740 : ∀ n : ℕ, 245490 ≤ n → n < 245740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_245490_245740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_245740_245990_check : checkFixedBlock 245740 250 = true := by
  decide +kernel

private theorem factorial_block_245740_245990 : ∀ n : ℕ, 245740 ≤ n → n < 245990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_245740_245990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_245990_246240_check : checkFixedBlock 245990 250 = true := by
  decide +kernel

private theorem factorial_block_245990_246240 : ∀ n : ℕ, 245990 ≤ n → n < 246240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_245990_246240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_246240_246490_check : checkFixedBlock 246240 250 = true := by
  decide +kernel

private theorem factorial_block_246240_246490 : ∀ n : ℕ, 246240 ≤ n → n < 246490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_246240_246490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_246490_246740_check : checkFixedBlock 246490 250 = true := by
  decide +kernel

private theorem factorial_block_246490_246740 : ∀ n : ℕ, 246490 ≤ n → n < 246740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_246490_246740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_246740_246990_check : checkFixedBlock 246740 250 = true := by
  decide +kernel

private theorem factorial_block_246740_246990 : ∀ n : ℕ, 246740 ≤ n → n < 246990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_246740_246990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_246990_247240_check : checkFixedBlock 246990 250 = true := by
  decide +kernel

private theorem factorial_block_246990_247240 : ∀ n : ℕ, 246990 ≤ n → n < 247240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_246990_247240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_247240_247490_check : checkFixedBlock 247240 250 = true := by
  decide +kernel

private theorem factorial_block_247240_247490 : ∀ n : ℕ, 247240 ≤ n → n < 247490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_247240_247490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_247490_247740_check : checkFixedBlock 247490 250 = true := by
  decide +kernel

private theorem factorial_block_247490_247740 : ∀ n : ℕ, 247490 ≤ n → n < 247740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_247490_247740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_247740_247990_check : checkFixedBlock 247740 250 = true := by
  decide +kernel

private theorem factorial_block_247740_247990 : ∀ n : ℕ, 247740 ≤ n → n < 247990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_247740_247990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_247990_248240_check : checkFixedBlock 247990 250 = true := by
  decide +kernel

private theorem factorial_block_247990_248240 : ∀ n : ℕ, 247990 ≤ n → n < 248240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_247990_248240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_248240_248490_check : checkFixedBlock 248240 250 = true := by
  decide +kernel

private theorem factorial_block_248240_248490 : ∀ n : ℕ, 248240 ≤ n → n < 248490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_248240_248490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_248490_248740_check : checkFixedBlock 248490 250 = true := by
  decide +kernel

private theorem factorial_block_248490_248740 : ∀ n : ℕ, 248490 ≤ n → n < 248740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_248490_248740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_248740_248990_check : checkFixedBlock 248740 250 = true := by
  decide +kernel

private theorem factorial_block_248740_248990 : ∀ n : ℕ, 248740 ≤ n → n < 248990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_248740_248990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_248990_249240_check : checkFixedBlock 248990 250 = true := by
  decide +kernel

private theorem factorial_block_248990_249240 : ∀ n : ℕ, 248990 ≤ n → n < 249240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_248990_249240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_249240_249490_check : checkFixedBlock 249240 250 = true := by
  decide +kernel

private theorem factorial_block_249240_249490 : ∀ n : ℕ, 249240 ≤ n → n < 249490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_249240_249490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_249490_249740_check : checkFixedBlock 249490 250 = true := by
  decide +kernel

private theorem factorial_block_249490_249740 : ∀ n : ℕ, 249490 ≤ n → n < 249740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_249490_249740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_249740_249990_check : checkFixedBlock 249740 250 = true := by
  decide +kernel

private theorem factorial_block_249740_249990 : ∀ n : ℕ, 249740 ≤ n → n < 249990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_249740_249990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_249990_250240_check : checkFixedBlock 249990 250 = true := by
  decide +kernel

private theorem factorial_block_249990_250240 : ∀ n : ℕ, 249990 ≤ n → n < 250240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_249990_250240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_250240_250490_check : checkFixedBlock 250240 250 = true := by
  decide +kernel

private theorem factorial_block_250240_250490 : ∀ n : ℕ, 250240 ≤ n → n < 250490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_250240_250490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_250490_250740_check : checkFixedBlock 250490 250 = true := by
  decide +kernel

private theorem factorial_block_250490_250740 : ∀ n : ℕ, 250490 ≤ n → n < 250740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_250490_250740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_250740_250990_check : checkFixedBlock 250740 250 = true := by
  decide +kernel

private theorem factorial_block_250740_250990 : ∀ n : ℕ, 250740 ≤ n → n < 250990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_250740_250990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_250990_251240_check : checkFixedBlock 250990 250 = true := by
  decide +kernel

private theorem factorial_block_250990_251240 : ∀ n : ℕ, 250990 ≤ n → n < 251240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_250990_251240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_251240_251490_check : checkFixedBlock 251240 250 = true := by
  decide +kernel

private theorem factorial_block_251240_251490 : ∀ n : ℕ, 251240 ≤ n → n < 251490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_251240_251490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_251490_251740_check : checkFixedBlock 251490 250 = true := by
  decide +kernel

private theorem factorial_block_251490_251740 : ∀ n : ℕ, 251490 ≤ n → n < 251740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_251490_251740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_251740_251990_check : checkFixedBlock 251740 250 = true := by
  decide +kernel

private theorem factorial_block_251740_251990 : ∀ n : ℕ, 251740 ≤ n → n < 251990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_251740_251990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_251990_252240_check : checkFixedBlock 251990 250 = true := by
  decide +kernel

private theorem factorial_block_251990_252240 : ∀ n : ℕ, 251990 ≤ n → n < 252240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_251990_252240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_252240_252490_check : checkFixedBlock 252240 250 = true := by
  decide +kernel

private theorem factorial_block_252240_252490 : ∀ n : ℕ, 252240 ≤ n → n < 252490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_252240_252490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_252490_252740_check : checkFixedBlock 252490 250 = true := by
  decide +kernel

private theorem factorial_block_252490_252740 : ∀ n : ℕ, 252490 ≤ n → n < 252740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_252490_252740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_252740_252990_check : checkFixedBlock 252740 250 = true := by
  decide +kernel

private theorem factorial_block_252740_252990 : ∀ n : ℕ, 252740 ≤ n → n < 252990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_252740_252990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_252990_253240_check : checkFixedBlock 252990 250 = true := by
  decide +kernel

private theorem factorial_block_252990_253240 : ∀ n : ℕ, 252990 ≤ n → n < 253240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_252990_253240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_253240_253490_check : checkFixedBlock 253240 250 = true := by
  decide +kernel

private theorem factorial_block_253240_253490 : ∀ n : ℕ, 253240 ≤ n → n < 253490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_253240_253490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_253490_253740_check : checkFixedBlock 253490 250 = true := by
  decide +kernel

private theorem factorial_block_253490_253740 : ∀ n : ℕ, 253490 ≤ n → n < 253740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_253490_253740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_253740_253990_check : checkFixedBlock 253740 250 = true := by
  decide +kernel

private theorem factorial_block_253740_253990 : ∀ n : ℕ, 253740 ≤ n → n < 253990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_253740_253990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_253990_254240_check : checkFixedBlock 253990 250 = true := by
  decide +kernel

private theorem factorial_block_253990_254240 : ∀ n : ℕ, 253990 ≤ n → n < 254240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_253990_254240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_254240_254490_check : checkFixedBlock 254240 250 = true := by
  decide +kernel

private theorem factorial_block_254240_254490 : ∀ n : ℕ, 254240 ≤ n → n < 254490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_254240_254490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_254490_254740_check : checkFixedBlock 254490 250 = true := by
  decide +kernel

private theorem factorial_block_254490_254740 : ∀ n : ℕ, 254490 ≤ n → n < 254740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_254490_254740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_254740_254990_check : checkFixedBlock 254740 250 = true := by
  decide +kernel

private theorem factorial_block_254740_254990 : ∀ n : ℕ, 254740 ≤ n → n < 254990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_254740_254990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_254990_255240_check : checkFixedBlock 254990 250 = true := by
  decide +kernel

private theorem factorial_block_254990_255240 : ∀ n : ℕ, 254990 ≤ n → n < 255240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_254990_255240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_255240_255490_check : checkFixedBlock 255240 250 = true := by
  decide +kernel

private theorem factorial_block_255240_255490 : ∀ n : ℕ, 255240 ≤ n → n < 255490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_255240_255490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_255490_255740_check : checkFixedBlock 255490 250 = true := by
  decide +kernel

private theorem factorial_block_255490_255740 : ∀ n : ℕ, 255490 ≤ n → n < 255740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_255490_255740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_255740_255990_check : checkFixedBlock 255740 250 = true := by
  decide +kernel

private theorem factorial_block_255740_255990 : ∀ n : ℕ, 255740 ≤ n → n < 255990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_255740_255990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_255990_256240_check : checkFixedBlock 255990 250 = true := by
  decide +kernel

private theorem factorial_block_255990_256240 : ∀ n : ℕ, 255990 ≤ n → n < 256240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_255990_256240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_256240_256490_check : checkFixedBlock 256240 250 = true := by
  decide +kernel

private theorem factorial_block_256240_256490 : ∀ n : ℕ, 256240 ≤ n → n < 256490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_256240_256490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_256490_256740_check : checkFixedBlock 256490 250 = true := by
  decide +kernel

private theorem factorial_block_256490_256740 : ∀ n : ℕ, 256490 ≤ n → n < 256740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_256490_256740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_256740_256990_check : checkFixedBlock 256740 250 = true := by
  decide +kernel

private theorem factorial_block_256740_256990 : ∀ n : ℕ, 256740 ≤ n → n < 256990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_256740_256990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_256990_257240_check : checkFixedBlock 256990 250 = true := by
  decide +kernel

private theorem factorial_block_256990_257240 : ∀ n : ℕ, 256990 ≤ n → n < 257240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_256990_257240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_257240_257490_check : checkFixedBlock 257240 250 = true := by
  decide +kernel

private theorem factorial_block_257240_257490 : ∀ n : ℕ, 257240 ≤ n → n < 257490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_257240_257490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_257490_257740_check : checkFixedBlock 257490 250 = true := by
  decide +kernel

private theorem factorial_block_257490_257740 : ∀ n : ℕ, 257490 ≤ n → n < 257740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_257490_257740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_257740_257990_check : checkFixedBlock 257740 250 = true := by
  decide +kernel

private theorem factorial_block_257740_257990 : ∀ n : ℕ, 257740 ≤ n → n < 257990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_257740_257990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_257990_258240_check : checkFixedBlock 257990 250 = true := by
  decide +kernel

private theorem factorial_block_257990_258240 : ∀ n : ℕ, 257990 ≤ n → n < 258240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_257990_258240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_258240_258490_check : checkFixedBlock 258240 250 = true := by
  decide +kernel

private theorem factorial_block_258240_258490 : ∀ n : ℕ, 258240 ≤ n → n < 258490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_258240_258490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_258490_258740_check : checkFixedBlock 258490 250 = true := by
  decide +kernel

private theorem factorial_block_258490_258740 : ∀ n : ℕ, 258490 ≤ n → n < 258740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_258490_258740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_258740_258990_check : checkFixedBlock 258740 250 = true := by
  decide +kernel

private theorem factorial_block_258740_258990 : ∀ n : ℕ, 258740 ≤ n → n < 258990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_258740_258990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_258990_259240_check : checkFixedBlock 258990 250 = true := by
  decide +kernel

private theorem factorial_block_258990_259240 : ∀ n : ℕ, 258990 ≤ n → n < 259240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_258990_259240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_259240_259490_check : checkFixedBlock 259240 250 = true := by
  decide +kernel

private theorem factorial_block_259240_259490 : ∀ n : ℕ, 259240 ≤ n → n < 259490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_259240_259490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_259490_259740_check : checkFixedBlock 259490 250 = true := by
  decide +kernel

private theorem factorial_block_259490_259740 : ∀ n : ℕ, 259490 ≤ n → n < 259740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_259490_259740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_259740_259990_check : checkFixedBlock 259740 250 = true := by
  decide +kernel

private theorem factorial_block_259740_259990 : ∀ n : ℕ, 259740 ≤ n → n < 259990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_259740_259990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_259990_260240_check : checkFixedBlock 259990 250 = true := by
  decide +kernel

private theorem factorial_block_259990_260240 : ∀ n : ℕ, 259990 ≤ n → n < 260240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_259990_260240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_260240_260490_check : checkFixedBlock 260240 250 = true := by
  decide +kernel

private theorem factorial_block_260240_260490 : ∀ n : ℕ, 260240 ≤ n → n < 260490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_260240_260490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_260490_260740_check : checkFixedBlock 260490 250 = true := by
  decide +kernel

private theorem factorial_block_260490_260740 : ∀ n : ℕ, 260490 ≤ n → n < 260740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_260490_260740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_260740_260990_check : checkFixedBlock 260740 250 = true := by
  decide +kernel

private theorem factorial_block_260740_260990 : ∀ n : ℕ, 260740 ≤ n → n < 260990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_260740_260990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_260990_261240_check : checkFixedBlock 260990 250 = true := by
  decide +kernel

private theorem factorial_block_260990_261240 : ∀ n : ℕ, 260990 ≤ n → n < 261240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_260990_261240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_261240_261490_check : checkFixedBlock 261240 250 = true := by
  decide +kernel

private theorem factorial_block_261240_261490 : ∀ n : ℕ, 261240 ≤ n → n < 261490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_261240_261490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_261490_261740_check : checkFixedBlock 261490 250 = true := by
  decide +kernel

private theorem factorial_block_261490_261740 : ∀ n : ℕ, 261490 ≤ n → n < 261740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_261490_261740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_261740_261990_check : checkFixedBlock 261740 250 = true := by
  decide +kernel

private theorem factorial_block_261740_261990 : ∀ n : ℕ, 261740 ≤ n → n < 261990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_261740_261990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_261990_262240_check : checkFixedBlock 261990 250 = true := by
  decide +kernel

private theorem factorial_block_261990_262240 : ∀ n : ℕ, 261990 ≤ n → n < 262240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_261990_262240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_262240_262490_check : checkFixedBlock 262240 250 = true := by
  decide +kernel

private theorem factorial_block_262240_262490 : ∀ n : ℕ, 262240 ≤ n → n < 262490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_262240_262490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_262490_262740_check : checkFixedBlock 262490 250 = true := by
  decide +kernel

private theorem factorial_block_262490_262740 : ∀ n : ℕ, 262490 ≤ n → n < 262740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_262490_262740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_262740_262990_check : checkFixedBlock 262740 250 = true := by
  decide +kernel

private theorem factorial_block_262740_262990 : ∀ n : ℕ, 262740 ≤ n → n < 262990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_262740_262990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_262990_263240_check : checkFixedBlock 262990 250 = true := by
  decide +kernel

private theorem factorial_block_262990_263240 : ∀ n : ℕ, 262990 ≤ n → n < 263240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_262990_263240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_263240_263490_check : checkFixedBlock 263240 250 = true := by
  decide +kernel

private theorem factorial_block_263240_263490 : ∀ n : ℕ, 263240 ≤ n → n < 263490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_263240_263490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_263490_263740_check : checkFixedBlock 263490 250 = true := by
  decide +kernel

private theorem factorial_block_263490_263740 : ∀ n : ℕ, 263490 ≤ n → n < 263740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_263490_263740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_263740_263990_check : checkFixedBlock 263740 250 = true := by
  decide +kernel

private theorem factorial_block_263740_263990 : ∀ n : ℕ, 263740 ≤ n → n < 263990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_263740_263990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_263990_264240_check : checkFixedBlock 263990 250 = true := by
  decide +kernel

private theorem factorial_block_263990_264240 : ∀ n : ℕ, 263990 ≤ n → n < 264240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_263990_264240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_264240_264490_check : checkFixedBlock 264240 250 = true := by
  decide +kernel

private theorem factorial_block_264240_264490 : ∀ n : ℕ, 264240 ≤ n → n < 264490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_264240_264490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_264490_264740_check : checkFixedBlock 264490 250 = true := by
  decide +kernel

private theorem factorial_block_264490_264740 : ∀ n : ℕ, 264490 ≤ n → n < 264740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_264490_264740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_264740_264990_check : checkFixedBlock 264740 250 = true := by
  decide +kernel

private theorem factorial_block_264740_264990 : ∀ n : ℕ, 264740 ≤ n → n < 264990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_264740_264990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_264990_265240_check : checkFixedBlock 264990 250 = true := by
  decide +kernel

private theorem factorial_block_264990_265240 : ∀ n : ℕ, 264990 ≤ n → n < 265240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_264990_265240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_265240_265490_check : checkFixedBlock 265240 250 = true := by
  decide +kernel

private theorem factorial_block_265240_265490 : ∀ n : ℕ, 265240 ≤ n → n < 265490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_265240_265490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_265490_265740_check : checkFixedBlock 265490 250 = true := by
  decide +kernel

private theorem factorial_block_265490_265740 : ∀ n : ℕ, 265490 ≤ n → n < 265740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_265490_265740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_265740_265990_check : checkFixedBlock 265740 250 = true := by
  decide +kernel

private theorem factorial_block_265740_265990 : ∀ n : ℕ, 265740 ≤ n → n < 265990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_265740_265990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_265990_266240_check : checkFixedBlock 265990 250 = true := by
  decide +kernel

private theorem factorial_block_265990_266240 : ∀ n : ℕ, 265990 ≤ n → n < 266240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_265990_266240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_266240_266490_check : checkFixedBlock 266240 250 = true := by
  decide +kernel

private theorem factorial_block_266240_266490 : ∀ n : ℕ, 266240 ≤ n → n < 266490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_266240_266490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_266490_266740_check : checkFixedBlock 266490 250 = true := by
  decide +kernel

private theorem factorial_block_266490_266740 : ∀ n : ℕ, 266490 ≤ n → n < 266740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_266490_266740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_266740_266990_check : checkFixedBlock 266740 250 = true := by
  decide +kernel

private theorem factorial_block_266740_266990 : ∀ n : ℕ, 266740 ≤ n → n < 266990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_266740_266990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_266990_267240_check : checkFixedBlock 266990 250 = true := by
  decide +kernel

private theorem factorial_block_266990_267240 : ∀ n : ℕ, 266990 ≤ n → n < 267240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_266990_267240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_267240_267490_check : checkFixedBlock 267240 250 = true := by
  decide +kernel

private theorem factorial_block_267240_267490 : ∀ n : ℕ, 267240 ≤ n → n < 267490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_267240_267490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_267490_267740_check : checkFixedBlock 267490 250 = true := by
  decide +kernel

private theorem factorial_block_267490_267740 : ∀ n : ℕ, 267490 ≤ n → n < 267740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_267490_267740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_267740_267990_check : checkFixedBlock 267740 250 = true := by
  decide +kernel

private theorem factorial_block_267740_267990 : ∀ n : ℕ, 267740 ≤ n → n < 267990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_267740_267990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_267990_268240_check : checkFixedBlock 267990 250 = true := by
  decide +kernel

private theorem factorial_block_267990_268240 : ∀ n : ℕ, 267990 ≤ n → n < 268240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_267990_268240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_268240_268490_check : checkFixedBlock 268240 250 = true := by
  decide +kernel

private theorem factorial_block_268240_268490 : ∀ n : ℕ, 268240 ≤ n → n < 268490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_268240_268490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_268490_268740_check : checkFixedBlock 268490 250 = true := by
  decide +kernel

private theorem factorial_block_268490_268740 : ∀ n : ℕ, 268490 ≤ n → n < 268740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_268490_268740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_268740_268990_check : checkFixedBlock 268740 250 = true := by
  decide +kernel

private theorem factorial_block_268740_268990 : ∀ n : ℕ, 268740 ≤ n → n < 268990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_268740_268990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_268990_269240_check : checkFixedBlock 268990 250 = true := by
  decide +kernel

private theorem factorial_block_268990_269240 : ∀ n : ℕ, 268990 ≤ n → n < 269240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_268990_269240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_269240_269490_check : checkFixedBlock 269240 250 = true := by
  decide +kernel

private theorem factorial_block_269240_269490 : ∀ n : ℕ, 269240 ≤ n → n < 269490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_269240_269490_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_269490_269740_check : checkFixedBlock 269490 250 = true := by
  decide +kernel

private theorem factorial_block_269490_269740 : ∀ n : ℕ, 269490 ≤ n → n < 269740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_269490_269740_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_269740_269990_check : checkFixedBlock 269740 250 = true := by
  decide +kernel

private theorem factorial_block_269740_269990 : ∀ n : ℕ, 269740 ≤ n → n < 269990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_269740_269990_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_269990_270240_check : checkFixedBlock 269990 250 = true := by
  decide +kernel

private theorem factorial_block_269990_270240 : ∀ n : ℕ, 269990 ≤ n → n < 270240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_269990_270240_check hlo hhi


set_option maxHeartbeats 0 in
-- Exact kernel verification of this fixed leaf of at most 250 inputs.
private theorem factorial_block_270240_270270_check : checkFixedBlock 270240 30 = true := by
  decide +kernel

private theorem factorial_block_270240_270270 : ∀ n : ℕ, 270240 ≤ n → n < 270270 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := by
  intro n hlo hhi
  exact checkFixedBlock_sound factorial_block_270240_270270_check hlo hhi


private theorem factorial_join_240490_240990 : ∀ n : ℕ, 240490 ≤ n → n < 240990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_240490_240740 factorial_block_240740_240990


private theorem factorial_join_240240_240990 : ∀ n : ℕ, 240240 ≤ n → n < 240990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_240240_240490 factorial_join_240490_240990


private theorem factorial_join_240990_241490 : ∀ n : ℕ, 240990 ≤ n → n < 241490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_240990_241240 factorial_block_241240_241490


private theorem factorial_join_241490_241990 : ∀ n : ℕ, 241490 ≤ n → n < 241990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_241490_241740 factorial_block_241740_241990


private theorem factorial_join_240990_241990 : ∀ n : ℕ, 240990 ≤ n → n < 241990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_240990_241490 factorial_join_241490_241990


private theorem factorial_join_240240_241990 : ∀ n : ℕ, 240240 ≤ n → n < 241990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_240240_240990 factorial_join_240990_241990


private theorem factorial_join_241990_242490 : ∀ n : ℕ, 241990 ≤ n → n < 242490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_241990_242240 factorial_block_242240_242490


private theorem factorial_join_242490_242990 : ∀ n : ℕ, 242490 ≤ n → n < 242990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_242490_242740 factorial_block_242740_242990


private theorem factorial_join_241990_242990 : ∀ n : ℕ, 241990 ≤ n → n < 242990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_241990_242490 factorial_join_242490_242990


private theorem factorial_join_242990_243490 : ∀ n : ℕ, 242990 ≤ n → n < 243490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_242990_243240 factorial_block_243240_243490


private theorem factorial_join_243490_243990 : ∀ n : ℕ, 243490 ≤ n → n < 243990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_243490_243740 factorial_block_243740_243990


private theorem factorial_join_242990_243990 : ∀ n : ℕ, 242990 ≤ n → n < 243990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_242990_243490 factorial_join_243490_243990


private theorem factorial_join_241990_243990 : ∀ n : ℕ, 241990 ≤ n → n < 243990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_241990_242990 factorial_join_242990_243990


private theorem factorial_join_240240_243990 : ∀ n : ℕ, 240240 ≤ n → n < 243990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_240240_241990 factorial_join_241990_243990


private theorem factorial_join_244240_244740 : ∀ n : ℕ, 244240 ≤ n → n < 244740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_244240_244490 factorial_block_244490_244740


private theorem factorial_join_243990_244740 : ∀ n : ℕ, 243990 ≤ n → n < 244740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_243990_244240 factorial_join_244240_244740


private theorem factorial_join_244740_245240 : ∀ n : ℕ, 244740 ≤ n → n < 245240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_244740_244990 factorial_block_244990_245240


private theorem factorial_join_245240_245740 : ∀ n : ℕ, 245240 ≤ n → n < 245740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_245240_245490 factorial_block_245490_245740


private theorem factorial_join_244740_245740 : ∀ n : ℕ, 244740 ≤ n → n < 245740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_244740_245240 factorial_join_245240_245740


private theorem factorial_join_243990_245740 : ∀ n : ℕ, 243990 ≤ n → n < 245740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_243990_244740 factorial_join_244740_245740


private theorem factorial_join_245740_246240 : ∀ n : ℕ, 245740 ≤ n → n < 246240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_245740_245990 factorial_block_245990_246240


private theorem factorial_join_246240_246740 : ∀ n : ℕ, 246240 ≤ n → n < 246740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_246240_246490 factorial_block_246490_246740


private theorem factorial_join_245740_246740 : ∀ n : ℕ, 245740 ≤ n → n < 246740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_245740_246240 factorial_join_246240_246740


private theorem factorial_join_246740_247240 : ∀ n : ℕ, 246740 ≤ n → n < 247240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_246740_246990 factorial_block_246990_247240


private theorem factorial_join_247240_247740 : ∀ n : ℕ, 247240 ≤ n → n < 247740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_247240_247490 factorial_block_247490_247740


private theorem factorial_join_246740_247740 : ∀ n : ℕ, 246740 ≤ n → n < 247740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_246740_247240 factorial_join_247240_247740


private theorem factorial_join_245740_247740 : ∀ n : ℕ, 245740 ≤ n → n < 247740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_245740_246740 factorial_join_246740_247740


private theorem factorial_join_243990_247740 : ∀ n : ℕ, 243990 ≤ n → n < 247740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_243990_245740 factorial_join_245740_247740


private theorem factorial_join_240240_247740 : ∀ n : ℕ, 240240 ≤ n → n < 247740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_240240_243990 factorial_join_243990_247740


private theorem factorial_join_247990_248490 : ∀ n : ℕ, 247990 ≤ n → n < 248490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_247990_248240 factorial_block_248240_248490


private theorem factorial_join_247740_248490 : ∀ n : ℕ, 247740 ≤ n → n < 248490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_247740_247990 factorial_join_247990_248490


private theorem factorial_join_248490_248990 : ∀ n : ℕ, 248490 ≤ n → n < 248990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_248490_248740 factorial_block_248740_248990


private theorem factorial_join_248990_249490 : ∀ n : ℕ, 248990 ≤ n → n < 249490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_248990_249240 factorial_block_249240_249490


private theorem factorial_join_248490_249490 : ∀ n : ℕ, 248490 ≤ n → n < 249490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_248490_248990 factorial_join_248990_249490


private theorem factorial_join_247740_249490 : ∀ n : ℕ, 247740 ≤ n → n < 249490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_247740_248490 factorial_join_248490_249490


private theorem factorial_join_249490_249990 : ∀ n : ℕ, 249490 ≤ n → n < 249990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_249490_249740 factorial_block_249740_249990


private theorem factorial_join_249990_250490 : ∀ n : ℕ, 249990 ≤ n → n < 250490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_249990_250240 factorial_block_250240_250490


private theorem factorial_join_249490_250490 : ∀ n : ℕ, 249490 ≤ n → n < 250490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_249490_249990 factorial_join_249990_250490


private theorem factorial_join_250490_250990 : ∀ n : ℕ, 250490 ≤ n → n < 250990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_250490_250740 factorial_block_250740_250990


private theorem factorial_join_250990_251490 : ∀ n : ℕ, 250990 ≤ n → n < 251490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_250990_251240 factorial_block_251240_251490


private theorem factorial_join_250490_251490 : ∀ n : ℕ, 250490 ≤ n → n < 251490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_250490_250990 factorial_join_250990_251490


private theorem factorial_join_249490_251490 : ∀ n : ℕ, 249490 ≤ n → n < 251490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_249490_250490 factorial_join_250490_251490


private theorem factorial_join_247740_251490 : ∀ n : ℕ, 247740 ≤ n → n < 251490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_247740_249490 factorial_join_249490_251490


private theorem factorial_join_251740_252240 : ∀ n : ℕ, 251740 ≤ n → n < 252240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_251740_251990 factorial_block_251990_252240


private theorem factorial_join_251490_252240 : ∀ n : ℕ, 251490 ≤ n → n < 252240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_251490_251740 factorial_join_251740_252240


private theorem factorial_join_252240_252740 : ∀ n : ℕ, 252240 ≤ n → n < 252740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_252240_252490 factorial_block_252490_252740


private theorem factorial_join_252740_253240 : ∀ n : ℕ, 252740 ≤ n → n < 253240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_252740_252990 factorial_block_252990_253240


private theorem factorial_join_252240_253240 : ∀ n : ℕ, 252240 ≤ n → n < 253240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_252240_252740 factorial_join_252740_253240


private theorem factorial_join_251490_253240 : ∀ n : ℕ, 251490 ≤ n → n < 253240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_251490_252240 factorial_join_252240_253240


private theorem factorial_join_253240_253740 : ∀ n : ℕ, 253240 ≤ n → n < 253740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_253240_253490 factorial_block_253490_253740


private theorem factorial_join_253740_254240 : ∀ n : ℕ, 253740 ≤ n → n < 254240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_253740_253990 factorial_block_253990_254240


private theorem factorial_join_253240_254240 : ∀ n : ℕ, 253240 ≤ n → n < 254240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_253240_253740 factorial_join_253740_254240


private theorem factorial_join_254240_254740 : ∀ n : ℕ, 254240 ≤ n → n < 254740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_254240_254490 factorial_block_254490_254740


private theorem factorial_join_254740_255240 : ∀ n : ℕ, 254740 ≤ n → n < 255240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_254740_254990 factorial_block_254990_255240


private theorem factorial_join_254240_255240 : ∀ n : ℕ, 254240 ≤ n → n < 255240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_254240_254740 factorial_join_254740_255240


private theorem factorial_join_253240_255240 : ∀ n : ℕ, 253240 ≤ n → n < 255240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_253240_254240 factorial_join_254240_255240


private theorem factorial_join_251490_255240 : ∀ n : ℕ, 251490 ≤ n → n < 255240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_251490_253240 factorial_join_253240_255240


private theorem factorial_join_247740_255240 : ∀ n : ℕ, 247740 ≤ n → n < 255240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_247740_251490 factorial_join_251490_255240


private theorem factorial_join_240240_255240 : ∀ n : ℕ, 240240 ≤ n → n < 255240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_240240_247740 factorial_join_247740_255240


private theorem factorial_join_255490_255990 : ∀ n : ℕ, 255490 ≤ n → n < 255990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_255490_255740 factorial_block_255740_255990


private theorem factorial_join_255240_255990 : ∀ n : ℕ, 255240 ≤ n → n < 255990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_255240_255490 factorial_join_255490_255990


private theorem factorial_join_255990_256490 : ∀ n : ℕ, 255990 ≤ n → n < 256490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_255990_256240 factorial_block_256240_256490


private theorem factorial_join_256490_256990 : ∀ n : ℕ, 256490 ≤ n → n < 256990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_256490_256740 factorial_block_256740_256990


private theorem factorial_join_255990_256990 : ∀ n : ℕ, 255990 ≤ n → n < 256990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_255990_256490 factorial_join_256490_256990


private theorem factorial_join_255240_256990 : ∀ n : ℕ, 255240 ≤ n → n < 256990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_255240_255990 factorial_join_255990_256990


private theorem factorial_join_256990_257490 : ∀ n : ℕ, 256990 ≤ n → n < 257490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_256990_257240 factorial_block_257240_257490


private theorem factorial_join_257490_257990 : ∀ n : ℕ, 257490 ≤ n → n < 257990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_257490_257740 factorial_block_257740_257990


private theorem factorial_join_256990_257990 : ∀ n : ℕ, 256990 ≤ n → n < 257990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_256990_257490 factorial_join_257490_257990


private theorem factorial_join_257990_258490 : ∀ n : ℕ, 257990 ≤ n → n < 258490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_257990_258240 factorial_block_258240_258490


private theorem factorial_join_258490_258990 : ∀ n : ℕ, 258490 ≤ n → n < 258990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_258490_258740 factorial_block_258740_258990


private theorem factorial_join_257990_258990 : ∀ n : ℕ, 257990 ≤ n → n < 258990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_257990_258490 factorial_join_258490_258990


private theorem factorial_join_256990_258990 : ∀ n : ℕ, 256990 ≤ n → n < 258990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_256990_257990 factorial_join_257990_258990


private theorem factorial_join_255240_258990 : ∀ n : ℕ, 255240 ≤ n → n < 258990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_255240_256990 factorial_join_256990_258990


private theorem factorial_join_259240_259740 : ∀ n : ℕ, 259240 ≤ n → n < 259740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_259240_259490 factorial_block_259490_259740


private theorem factorial_join_258990_259740 : ∀ n : ℕ, 258990 ≤ n → n < 259740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_258990_259240 factorial_join_259240_259740


private theorem factorial_join_259740_260240 : ∀ n : ℕ, 259740 ≤ n → n < 260240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_259740_259990 factorial_block_259990_260240


private theorem factorial_join_260240_260740 : ∀ n : ℕ, 260240 ≤ n → n < 260740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_260240_260490 factorial_block_260490_260740


private theorem factorial_join_259740_260740 : ∀ n : ℕ, 259740 ≤ n → n < 260740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_259740_260240 factorial_join_260240_260740


private theorem factorial_join_258990_260740 : ∀ n : ℕ, 258990 ≤ n → n < 260740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_258990_259740 factorial_join_259740_260740


private theorem factorial_join_260740_261240 : ∀ n : ℕ, 260740 ≤ n → n < 261240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_260740_260990 factorial_block_260990_261240


private theorem factorial_join_261240_261740 : ∀ n : ℕ, 261240 ≤ n → n < 261740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_261240_261490 factorial_block_261490_261740


private theorem factorial_join_260740_261740 : ∀ n : ℕ, 260740 ≤ n → n < 261740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_260740_261240 factorial_join_261240_261740


private theorem factorial_join_261740_262240 : ∀ n : ℕ, 261740 ≤ n → n < 262240 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_261740_261990 factorial_block_261990_262240


private theorem factorial_join_262240_262740 : ∀ n : ℕ, 262240 ≤ n → n < 262740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_262240_262490 factorial_block_262490_262740


private theorem factorial_join_261740_262740 : ∀ n : ℕ, 261740 ≤ n → n < 262740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_261740_262240 factorial_join_262240_262740


private theorem factorial_join_260740_262740 : ∀ n : ℕ, 260740 ≤ n → n < 262740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_260740_261740 factorial_join_261740_262740


private theorem factorial_join_258990_262740 : ∀ n : ℕ, 258990 ≤ n → n < 262740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_258990_260740 factorial_join_260740_262740


private theorem factorial_join_255240_262740 : ∀ n : ℕ, 255240 ≤ n → n < 262740 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_255240_258990 factorial_join_258990_262740


private theorem factorial_join_262990_263490 : ∀ n : ℕ, 262990 ≤ n → n < 263490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_262990_263240 factorial_block_263240_263490


private theorem factorial_join_262740_263490 : ∀ n : ℕ, 262740 ≤ n → n < 263490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_262740_262990 factorial_join_262990_263490


private theorem factorial_join_263490_263990 : ∀ n : ℕ, 263490 ≤ n → n < 263990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_263490_263740 factorial_block_263740_263990


private theorem factorial_join_263990_264490 : ∀ n : ℕ, 263990 ≤ n → n < 264490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_263990_264240 factorial_block_264240_264490


private theorem factorial_join_263490_264490 : ∀ n : ℕ, 263490 ≤ n → n < 264490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_263490_263990 factorial_join_263990_264490


private theorem factorial_join_262740_264490 : ∀ n : ℕ, 262740 ≤ n → n < 264490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_262740_263490 factorial_join_263490_264490


private theorem factorial_join_264490_264990 : ∀ n : ℕ, 264490 ≤ n → n < 264990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_264490_264740 factorial_block_264740_264990


private theorem factorial_join_264990_265490 : ∀ n : ℕ, 264990 ≤ n → n < 265490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_264990_265240 factorial_block_265240_265490


private theorem factorial_join_264490_265490 : ∀ n : ℕ, 264490 ≤ n → n < 265490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_264490_264990 factorial_join_264990_265490


private theorem factorial_join_265490_265990 : ∀ n : ℕ, 265490 ≤ n → n < 265990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_265490_265740 factorial_block_265740_265990


private theorem factorial_join_265990_266490 : ∀ n : ℕ, 265990 ≤ n → n < 266490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_265990_266240 factorial_block_266240_266490


private theorem factorial_join_265490_266490 : ∀ n : ℕ, 265490 ≤ n → n < 266490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_265490_265990 factorial_join_265990_266490


private theorem factorial_join_264490_266490 : ∀ n : ℕ, 264490 ≤ n → n < 266490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_264490_265490 factorial_join_265490_266490


private theorem factorial_join_262740_266490 : ∀ n : ℕ, 262740 ≤ n → n < 266490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_262740_264490 factorial_join_264490_266490


private theorem factorial_join_266490_266990 : ∀ n : ℕ, 266490 ≤ n → n < 266990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_266490_266740 factorial_block_266740_266990


private theorem factorial_join_266990_267490 : ∀ n : ℕ, 266990 ≤ n → n < 267490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_266990_267240 factorial_block_267240_267490


private theorem factorial_join_266490_267490 : ∀ n : ℕ, 266490 ≤ n → n < 267490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_266490_266990 factorial_join_266990_267490


private theorem factorial_join_267490_267990 : ∀ n : ℕ, 267490 ≤ n → n < 267990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_267490_267740 factorial_block_267740_267990


private theorem factorial_join_267990_268490 : ∀ n : ℕ, 267990 ≤ n → n < 268490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_267990_268240 factorial_block_268240_268490


private theorem factorial_join_267490_268490 : ∀ n : ℕ, 267490 ≤ n → n < 268490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_267490_267990 factorial_join_267990_268490


private theorem factorial_join_266490_268490 : ∀ n : ℕ, 266490 ≤ n → n < 268490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_266490_267490 factorial_join_267490_268490


private theorem factorial_join_268490_268990 : ∀ n : ℕ, 268490 ≤ n → n < 268990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_268490_268740 factorial_block_268740_268990


private theorem factorial_join_268990_269490 : ∀ n : ℕ, 268990 ≤ n → n < 269490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_268990_269240 factorial_block_269240_269490


private theorem factorial_join_268490_269490 : ∀ n : ℕ, 268490 ≤ n → n < 269490 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_268490_268990 factorial_join_268990_269490


private theorem factorial_join_269490_269990 : ∀ n : ℕ, 269490 ≤ n → n < 269990 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_269490_269740 factorial_block_269740_269990


private theorem factorial_join_269990_270270 : ∀ n : ℕ, 269990 ≤ n → n < 270270 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_block_269990_270240 factorial_block_270240_270270


private theorem factorial_join_269490_270270 : ∀ n : ℕ, 269490 ≤ n → n < 270270 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_269490_269990 factorial_join_269990_270270


private theorem factorial_join_268490_270270 : ∀ n : ℕ, 268490 ≤ n → n < 270270 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_268490_269490 factorial_join_269490_270270


private theorem factorial_join_266490_270270 : ∀ n : ℕ, 266490 ≤ n → n < 270270 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_266490_268490 factorial_join_268490_270270


private theorem factorial_join_262740_270270 : ∀ n : ℕ, 262740 ≤ n → n < 270270 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_262740_266490 factorial_join_266490_270270


private theorem factorial_join_255240_270270 : ∀ n : ℕ, 255240 ≤ n → n < 270270 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_255240_262740 factorial_join_262740_270270


/-- Certified factorial-floor range [240240, 270270). -/

theorem factorial_certificate_08 : ∀ n : ℕ, 240240 ≤ n → n < 270270 →
    (if 0 < n ∧ n < 60 then (1000000 : ℤ) else 0) ≤
      floorNumerator factorialWeights n := floorBlock_join factorial_join_240240_255240 factorial_join_255240_270270


end RS12Factorial
