name = "solution_CH2_v1"
defaultTargets = ["ZetaInstance", "AdditiveCombination", "RectanglePort", "ResiduePort", "ZetaConjPort", "PntSupport", "PntAsymptotics", "PntSobolev", "PntSmooth", "PntFourier", "WienerPort", "Part1Fourier", "Approximants", "Decay", "Section5", "Section5Neg", "ZetaInstanceNeg", "Section6", "Section6Res", "Section6Zeros", "Section6Weight", "Section7", "DigammaReal", "Section8", "Section81", "Section6Contour", "ZetaReal01", "Section6Hyp", "Section7Zeros", "Section7Weights", "Section7Tritura", "Section7Adar", "Section7Vihuela", "Solution"]

[[require]]
name = "IEANTN"
path = "../.."

[[lean_lib]]
name = "AdditiveCombination"
roots = ["AdditiveCombination"]

[[lean_lib]]
name = "RectanglePort"
roots = ["RectanglePort"]

[[lean_lib]]
name = "ResiduePort"
roots = ["ResiduePort"]

[[lean_lib]]
name = "ZetaConjPort"
roots = ["ZetaConjPort"]

[[lean_lib]]
name = "PntSupport"
roots = ["PntSupport"]

[[lean_lib]]
name = "PntAsymptotics"
roots = ["PntAsymptotics"]

[[lean_lib]]
name = "PntSobolev"
roots = ["PntSobolev"]

[[lean_lib]]
name = "PntSmooth"
roots = ["PntSmooth"]

[[lean_lib]]
name = "PntFourier"
roots = ["PntFourier"]

[[lean_lib]]
name = "WienerPort"
roots = ["WienerPort"]

[[lean_lib]]
name = "Part1Fourier"
roots = ["Part1Fourier"]

[[lean_lib]]
name = "Approximants"
roots = ["Approximants"]

[[lean_lib]]
name = "Decay"
roots = ["Decay"]

[[lean_lib]]
name = "Section5"
roots = ["Section5"]

[[lean_lib]]
name = "Section5Neg"
roots = ["Section5Neg"]

[[lean_lib]]
name = "ZetaInstanceNeg"
roots = ["ZetaInstanceNeg"]

[[lean_lib]]
name = "Section6"
roots = ["Section6"]

[[lean_lib]]
name = "Section6Res"
roots = ["Section6Res"]

[[lean_lib]]
name = "Section6Zeros"
roots = ["Section6Zeros"]

[[lean_lib]]
name = "Section6Weight"
roots = ["Section6Weight"]

[[lean_lib]]
name = "Section6Contour"
roots = ["Section6Contour"]

[[lean_lib]]
name = "ZetaReal01"
roots = ["ZetaReal01"]

[[lean_lib]]
name = "Section6Hyp"
roots = ["Section6Hyp"]

[[lean_lib]]
name = "Section7Zeros"
roots = ["Section7Zeros"]

[[lean_lib]]
name = "Section7Weights"
roots = ["Section7Weights"]

[[lean_lib]]
name = "Section7Tritura"
roots = ["Section7Tritura"]

[[lean_lib]]
name = "Section7Adar"
roots = ["Section7Adar"]

[[lean_lib]]
name = "Section7Vihuela"
roots = ["Section7Vihuela"]

[[lean_lib]]
name = "Section7"
roots = ["Section7"]

[[lean_lib]]
name = "DigammaReal"
roots = ["DigammaReal"]

[[lean_lib]]
name = "Section8"
roots = ["Section8"]

[[lean_lib]]
name = "Section81"
roots = ["Section81"]

[[lean_lib]]
name = "Solution"
roots = ["Solution"]

[[lean_lib]]
name = "ZetaInstance"
roots = ["ZetaInstance"]
