/-
Copyright (c) 2026 IEANTN contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Terence Tao
-/
import IEANTN.Nodes.BKLNW.v1.Tables
import IEANTN.Nodes.BKLNW.v1.Challenge
import IEANTN.Nodes.Brown1967.v1.Challenge
import IEANTN.Nodes.Buthe.v1.Challenge
import IEANTN.Nodes.Buthe.v2.Challenge
import IEANTN.Nodes.Buthe2016.v1.Challenge
import IEANTN.Nodes.ButheNumerics.v1.Challenge
import IEANTN.Nodes.CH2.v1.Challenge
import IEANTN.Nodes.CH2.v2.Challenge
import IEANTN.Nodes.CH2.v3.Challenge
import IEANTN.Nodes.CH2.v4.Challenge
import IEANTN.Nodes.ChengGraham2004.v1.Challenge
import IEANTN.Nodes.DudekPlatt.v1.Challenge
import IEANTN.Nodes.DudekPlatt.v2.Challenge
import IEANTN.Nodes.DudekPlatt.v3.Challenge
import IEANTN.Nodes.DudekPlattNumerics.v1.Challenge
import IEANTN.Nodes.DudekPlattNumerics.v2.Challenge
import IEANTN.Nodes.Dusart2018.v1.Challenge
import IEANTN.Nodes.FKBJ.v1.Challenge
import IEANTN.Nodes.FKS.v1.Challenge
import IEANTN.Nodes.FKS2.v1.Challenge
import IEANTN.Nodes.FKS2.v2.Challenge
import IEANTN.Nodes.FKS2Numerics.v1.Challenge
import IEANTN.Nodes.Hiary2016.v1.Challenge
import IEANTN.Nodes.KLN.v1.Challenge
import IEANTN.Nodes.Kadiri2005.v1.Challenge
import IEANTN.Nodes.Lcm.v1.Challenge
import IEANTN.Nodes.Lcm.v1.Examples
import IEANTN.Nodes.Lcm.v2.Challenge
import IEANTN.Nodes.MT.v1.Challenge
import IEANTN.Nodes.MTY.v1.Challenge
import IEANTN.Nodes.Platt2015.v1.Challenge
import IEANTN.Nodes.Platt2017.v1.Challenge
import IEANTN.Nodes.PlattTrudgian.v1.Challenge
import IEANTN.Nodes.PlattTrudgian2021.v1.Tables
import IEANTN.Nodes.PlattTrudgian2021.v1.Challenge
import IEANTN.Nodes.RosserSchoenfeld.v1.Challenge
import IEANTN.Nodes.Trudgian2011.v1.Challenge
import IEANTN.Nodes.Wedeniwski.v1.Challenge
import IEANTN.Nodes.ZeroFreeHeight.v1.Challenge

/-!
# The node network

**Generated file - do not edit.**  Regenerated by `python scripts/ieantn.py gen-challenges`.

Every node version's conclusions, generated challenge, and examples where present. Nodes are
versioned: a node lives at `IEANTN/Nodes/<Family>/<version>/` and its id is `<Family>.<version>`.
-/
