/-
Copyright (c) 2026 IEANTN contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Terence Tao
-/
import IEANTN.Nodes.Dusart2018.v1.Challenge
import IEANTN.Nodes.Lcm.v1.Challenge
import IEANTN.Nodes.Lcm.v1.Examples
import IEANTN.Nodes.Lcm.v2.Challenge

/-!
# The node network

**Generated file - do not edit.**  Regenerated by `python scripts/ieantn.py gen-challenges`.

Every node version's conclusions, generated challenge, and examples where present. Nodes are
versioned: a node lives at `IEANTN/Nodes/<Family>/<version>/` and its id is `<Family>.<version>`.
-/
