/-
Copyright (c) 2026 IEANTN contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Terence Tao
-/
import IEANTN.Nodes.ZeroCount.v1.Conclusions

/-!
# Challenge: `ZeroCount.v1`

**Generated file - do not edit.**  Regenerated by
`python scripts/ieantn.py gen-challenges` from `Conclusions.lean` and
`formalization.yaml`; CI diffs the two.

Each `sorry` below is deliberate and permanent: a challenge *states*, it does not prove.
How each conclusion is justified is recorded in `formalization.yaml`, not here.
-/

theorem ZeroCount.v1.challenge_rvm_error_bound : ZeroCount.v1.rvm_error_bound := by
  sorry

theorem ZeroCount.v1.challenge_rvm_error_small : ZeroCount.v1.rvm_error_small := by
  sorry
