/-
Copyright (c) 2026 IEANTN contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Taksh Kothari
-/
import IEANTN.Nodes.BKLNWNumerics.v1.Conclusions
import IEANTN.Nodes.Buthe.v1.Conclusions
import IEANTN.Nodes.Buthe2016.v1.Conclusions
import IEANTN.Nodes.PlattTrudgian2021.v1.Conclusions

/-!
# Challenge: `BKLNWNumerics.v1`

**Generated file - do not edit.**  Regenerated by
`python scripts/ieantn.py gen-challenges` from `Conclusions.lean` and
`formalization.yaml`; CI diffs the two.

Each `sorry` below is deliberate and permanent: a challenge *states*, it does not prove.
How each conclusion is justified is recorded in `formalization.yaml`, not here.
-/

theorem BKLNWNumerics.v1.challenge_table8_psi_bound
    (buthe2016_v1_theorem_2_psi : Buthe2016.v1.theorem_2_psi)
    (platttrudgian2021_v1_theorem_1_numerical : PlattTrudgian2021.v1.theorem_1_numerical) :
    BKLNWNumerics.v1.table8_psi_bound := by
  sorry

theorem BKLNWNumerics.v1.challenge_theta_error_le_one
    (buthe_v1_theorem_2_theta_lower : Buthe.v1.theorem_2_theta_lower) :
    BKLNWNumerics.v1.theta_error_le_one := by
  sorry
